(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"2HDM CPC",
  Authors -> {"Yongcheng Wu"},
  Version -> "0.1.2",
  Date -> "01. 09. 2019",
  Institutions -> {"Carleton University"},
  Emails -> {"ycwu@physics.carleton.ca"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[5], S[6]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HL",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHL,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HH",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHH,
    Indices -> {} },

S[3] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HA",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHA,
    Indices -> {} },

S[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "Hpm",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHp,
    Indices -> {} },

S[5] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = 1;
GaugeXi[ S[3] ] = 1;
GaugeXi[ S[4] ] = 1;
GaugeXi[ S[5] ] = GaugeXi[Z];
GaugeXi[ S[6] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MHL[ ___ ] := MHL;
MHH[ ___ ] := MHH;
MHA[ ___ ] := MHA;
MHp[ ___ ] := MHp;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc3, 0}, {I*gc3, 0}, {I*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {I*gc3, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc4, 0}, {(-I)*gc4, 0}, {(2*I)*gc4, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc5, 0}, {I*gc5, 0}, {I*gc5, 0}, {(-I)*gc5, 0}, {(-I)*gc5, 0}, {I*gc5, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc6, 0}, {(-I)*gc6, 0}, {(2*I)*gc6, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc7, 0}, {I*gc7, 0}, {I*gc7, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc8, 0}, {(-I)*gc8, 0}, {(2*I)*gc8, 0}},

C[ S[5] , S[5] , S[5] , S[5] ] == {{(-3*I)*(cb^4*lam1 + 2*cb^2*(lam3 + lam4 + lam5)*sb^2 + lam2*sb^4), 0}},

C[ S[5] , S[5] , S[6] , -S[6] ] == {{(-I)*(cb^4*lam1 + 2*cb^2*(lam3 + lam4 + lam5)*sb^2 + lam2*sb^4), 0}},

C[ S[6] , S[6] , -S[6] , -S[6] ] == {{(-2*I)*(cb^4*lam1 + 2*cb^2*(lam3 + lam4 + lam5)*sb^2 + lam2*sb^4), 0}},

C[ S[5] , S[5] , S[2] , S[2] ] == {{(-I)*(4*ca*cb*lam5*sa*sb + sa^2*(cb^2*(lam3 + lam4 - lam5) + lam2*sb^2) + ca^2*(cb^2*lam1 + (lam3 + lam4 - lam5)*sb^2)), 0}},

C[ S[6] , -S[6] , S[2] , S[2] ] == {{(-I)*(2*ca*cb*(lam4 + lam5)*sa*sb + sa^2*(cb^2*lam3 + lam2*sb^2) + ca^2*(cb^2*lam1 + lam3*sb^2)), 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-3*I)*(ca^4*lam1 + 2*ca^2*(lam3 + lam4 + lam5)*sa^2 + lam2*sa^4), 0}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{(-3*I)*(cb^4*lam2 + 2*cb^2*(lam3 + lam4 + lam5)*sb^2 + lam1*sb^4), 0}},

C[ S[3] , S[3] , S[1] , S[1] ] == {{(-I)*(4*ca*cb*lam5*sa*sb + sa^2*(cb^2*(lam3 + lam4 - lam5) + lam1*sb^2) + ca^2*(cb^2*lam2 + (lam3 + lam4 - lam5)*sb^2)), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-3*I)*(ca^4*lam2 + 2*ca^2*(lam3 + lam4 + lam5)*sa^2 + lam1*sa^4), 0}},

C[ S[3] , S[3] , S[4] , -S[4] ] == {{(-I)*(cb^4*lam2 + 2*cb^2*(lam3 + lam4 + lam5)*sb^2 + lam1*sb^4), 0}},

C[ S[1] , S[1] , S[4] , -S[4] ] == {{(-I)*(2*ca*cb*(lam4 + lam5)*sa*sb + sa^2*(cb^2*lam3 + lam1*sb^2) + ca^2*(cb^2*lam2 + lam3*sb^2)), 0}},

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*(cb^4*lam2 + 2*cb^2*(lam3 + lam4 + lam5)*sb^2 + lam1*sb^4), 0}},

C[ S[5] , S[5] , S[3] , S[3] ] == {{(-I)*(cb^4*(lam3 + lam4 + lam5) + cb^2*(3*lam1 + 3*lam2 - 4*(lam3 + lam4 + lam5))*sb^2 + (lam3 + lam4 + lam5)*sb^4), 0}},

C[ S[6] , -S[6] , S[3] , S[3] ] == {{(-I)*(cb^4*lam3 + cb^2*(lam1 + lam2 - 2*(lam4 + lam5))*sb^2 + lam3*sb^4), 0}},

C[ S[3] , S[3] , S[2] , S[2] ] == {{(-I)*(-4*ca*cb*lam5*sa*sb + ca^2*(cb^2*(lam3 + lam4 - lam5) + lam1*sb^2) + sa^2*(cb^2*lam2 + (lam3 + lam4 - lam5)*sb^2)), 0}},

C[ S[5] , S[5] , S[1] , S[1] ] == {{(-I)*(-4*ca*cb*lam5*sa*sb + ca^2*(cb^2*(lam3 + lam4 - lam5) + lam2*sb^2) + sa^2*(cb^2*lam1 + (lam3 + lam4 - lam5)*sb^2)), 0}},

C[ S[6] , -S[6] , S[1] , S[1] ] == {{(-I)*(-2*ca*cb*(lam4 + lam5)*sa*sb + ca^2*(cb^2*lam3 + lam2*sb^2) + sa^2*(cb^2*lam1 + lam3*sb^2)), 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-I)*(ca^4*(lam3 + lam4 + lam5) + ca^2*(3*lam1 + 3*lam2 - 4*(lam3 + lam4 + lam5))*sa^2 + (lam3 + lam4 + lam5)*sa^4), 0}},

C[ S[5] , S[5] , S[4] , -S[4] ] == {{(-I)*(cb^4*lam3 + cb^2*(lam1 + lam2 - 2*(lam4 + lam5))*sb^2 + lam3*sb^4), 0}},

C[ S[6] , -S[6] , S[4] , -S[4] ] == {{(-I)*(cb^4*(lam3 + lam4) + 2*cb^2*(lam1 + lam2 - lam3 - lam4 - 2*lam5)*sb^2 + (lam3 + lam4)*sb^4), 0}},

C[ S[2] , S[2] , S[4] , -S[4] ] == {{(-I)*(-2*ca*cb*(lam4 + lam5)*sa*sb + ca^2*(cb^2*lam3 + lam1*sb^2) + sa^2*(cb^2*lam2 + lam3*sb^2)), 0}},

C[ S[5] , -S[6] , S[3] , S[4] ] == {{(-I/2)*(cb^4*(lam4 + lam5) + 2*cb^2*(lam1 + lam2 - 2*lam3 - lam4 - lam5)*sb^2 + (lam4 + lam5)*sb^4), 0}},

C[ -S[6] , S[3] , S[2] , S[4] ] == {{-((lam4 - lam5)*(ca*cb + sa*sb)*(cb^2 + sb^2))/2, 0}},

C[ S[5] , -S[6] , S[1] , S[4] ] == {{((lam4 - lam5)*(ca*cb + sa*sb)*(cb^2 + sb^2))/2, 0}},

C[ -S[6] , S[2] , S[1] , S[4] ] == {{(-I/2)*(2*ca*cb*(lam1 + lam2 - 2*lam3)*sa*sb + ca^2*(lam4 + lam5)*(cb^2 - sb^2) - (lam4 + lam5)*sa^2*(cb^2 - sb^2)), 0}},

C[ S[5] , S[6] , S[3] , -S[4] ] == {{(-I/2)*(cb^4*(lam4 + lam5) + 2*cb^2*(lam1 + lam2 - 2*lam3 - lam4 - lam5)*sb^2 + (lam4 + lam5)*sb^4), 0}},

C[ S[6] , S[3] , S[2] , -S[4] ] == {{((lam4 - lam5)*(ca*cb + sa*sb)*(cb^2 + sb^2))/2, 0}},

C[ S[5] , S[6] , S[1] , -S[4] ] == {{-((lam4 - lam5)*(ca*cb + sa*sb)*(cb^2 + sb^2))/2, 0}},

C[ S[6] , S[2] , S[1] , -S[4] ] == {{(-I/2)*(2*ca*cb*(lam1 + lam2 - 2*lam3)*sa*sb + ca^2*(lam4 + lam5)*(cb^2 - sb^2) - (lam4 + lam5)*sa^2*(cb^2 - sb^2)), 0}},

C[ S[5] , S[3] , S[2] , S[1] ] == {{(-I)*(ca*cb*(lam1 + lam2 - 2*(lam3 + lam4 - lam5))*sa*sb + ca^2*lam5*(cb^2 - sb^2) + lam5*sa^2*(-cb^2 + sb^2)), 0}},

C[ -S[6] , -S[6] , S[4] , S[4] ] == {{(-2*I)*(cb^4*lam5 + cb^2*(lam1 + lam2 - 2*(lam3 + lam4))*sb^2 + lam5*sb^4), 0}},

C[ S[6] , S[6] , -S[4] , -S[4] ] == {{(-2*I)*(cb^4*lam5 + cb^2*(lam1 + lam2 - 2*(lam3 + lam4))*sb^2 + lam5*sb^4), 0}},

C[ S[5] , S[5] , S[2] , S[1] ] == {{(-I)*(2*ca^2*cb*lam5*sb - 2*cb*lam5*sa^2*sb + ca*sa*(cb^2*(-lam1 + lam3 + lam4 - lam5) + (lam2 - lam3 - lam4 + lam5)*sb^2)), 0}},

C[ S[6] , -S[6] , S[2] , S[1] ] == {{(-I)*(ca^2*cb*(lam4 + lam5)*sb - cb*(lam4 + lam5)*sa^2*sb + ca*sa*(cb^2*(-lam1 + lam3) + (lam2 - lam3)*sb^2)), 0}},

C[ S[2] , S[2] , S[2] , S[1] ] == {{(3*I)*ca*sa*(ca^2*(lam1 - lam3 - lam4 - lam5) + (-lam2 + lam3 + lam4 + lam5)*sa^2), 0}},

C[ S[3] , S[3] , S[2] , S[1] ] == {{I*(2*ca^2*cb*lam5*sb - 2*cb*lam5*sa^2*sb + ca*sa*(cb^2*(-lam2 + lam3 + lam4 - lam5) + (lam1 - lam3 - lam4 + lam5)*sb^2)), 0}},

C[ S[2] , S[1] , S[1] , S[1] ] == {{(-3*I)*ca*sa*(ca^2*(lam2 - lam3 - lam4 - lam5) + (-lam1 + lam3 + lam4 + lam5)*sa^2), 0}},

C[ S[2] , S[1] , S[4] , -S[4] ] == {{I*(ca^2*cb*(lam4 + lam5)*sb - cb*(lam4 + lam5)*sa^2*sb + ca*sa*(cb^2*(-lam2 + lam3) + (lam1 - lam3)*sb^2)), 0}},

C[ S[5] , -S[6] , S[2] , S[4] ] == {{((lam4 - lam5)*(cb*sa - ca*sb)*(cb^2 + sb^2))/2, 0}},

C[ -S[6] , S[2] , S[2] , S[4] ] == {{I*(ca^2*cb*(lam1 - lam3)*sb + cb*(-lam2 + lam3)*sa^2*sb - ca*(lam4 + lam5)*sa*(cb^2 - sb^2)), 0}},

C[ -S[6] , S[3] , S[1] , S[4] ] == {{((lam4 - lam5)*(cb*sa - ca*sb)*(cb^2 + sb^2))/2, 0}},

C[ -S[6] , S[1] , S[1] , S[4] ] == {{(-I)*(ca^2*cb*(lam2 - lam3)*sb + cb*(-lam1 + lam3)*sa^2*sb - ca*(lam4 + lam5)*sa*(cb^2 - sb^2)), 0}},

C[ S[5] , S[6] , S[2] , -S[4] ] == {{-((lam4 - lam5)*(cb*sa - ca*sb)*(cb^2 + sb^2))/2, 0}},

C[ S[6] , S[2] , S[2] , -S[4] ] == {{I*(ca^2*cb*(lam1 - lam3)*sb + cb*(-lam2 + lam3)*sa^2*sb - ca*(lam4 + lam5)*sa*(cb^2 - sb^2)), 0}},

C[ S[6] , S[3] , S[1] , -S[4] ] == {{-((lam4 - lam5)*(cb*sa - ca*sb)*(cb^2 + sb^2))/2, 0}},

C[ S[6] , S[1] , S[1] , -S[4] ] == {{(-I)*(ca^2*cb*(lam2 - lam3)*sb + cb*(-lam1 + lam3)*sa^2*sb - ca*(lam4 + lam5)*sa*(cb^2 - sb^2)), 0}},

C[ S[5] , S[3] , S[2] , S[2] ] == {{I*(ca^2*cb*(lam1 - lam3 - lam4 + lam5)*sb + cb*(-lam2 + lam3 + lam4 - lam5)*sa^2*sb + 2*ca*lam5*sa*(-cb^2 + sb^2)), 0}},

C[ S[5] , S[3] , S[1] , S[1] ] == {{(-I)*(ca^2*cb*(lam2 - lam3 - lam4 + lam5)*sb + cb*(-lam1 + lam3 + lam4 - lam5)*sa^2*sb + 2*ca*lam5*sa*(-cb^2 + sb^2)), 0}},

C[ S[5] , S[5] , S[5] , S[3] ] == {{(3*I)*cb*sb*(cb^2*(lam1 - lam3 - lam4 - lam5) + (-lam2 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ S[5] , S[6] , -S[6] , S[3] ] == {{I*cb*sb*(cb^2*(lam1 - lam3 - lam4 - lam5) + (-lam2 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ S[5] , S[5] , -S[6] , S[4] ] == {{I*cb*sb*(cb^2*(lam1 - lam3 - lam4 - lam5) + (-lam2 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ S[6] , -S[6] , -S[6] , S[4] ] == {{(2*I)*cb*sb*(cb^2*(lam1 - lam3 - lam4 - lam5) + (-lam2 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ S[5] , S[5] , S[6] , -S[4] ] == {{I*cb*sb*(cb^2*(lam1 - lam3 - lam4 - lam5) + (-lam2 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ S[6] , S[6] , -S[6] , -S[4] ] == {{(2*I)*cb*sb*(cb^2*(lam1 - lam3 - lam4 - lam5) + (-lam2 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ S[5] , S[3] , S[3] , S[3] ] == {{(-3*I)*cb*sb*(cb^2*(lam2 - lam3 - lam4 - lam5) + (-lam1 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ -S[6] , S[3] , S[3] , S[4] ] == {{(-I)*cb*sb*(cb^2*(lam2 - lam3 - lam4 - lam5) + (-lam1 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ S[6] , S[3] , S[3] , -S[4] ] == {{(-I)*cb*sb*(cb^2*(lam2 - lam3 - lam4 - lam5) + (-lam1 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ S[5] , S[3] , S[4] , -S[4] ] == {{(-I)*cb*sb*(cb^2*(lam2 - lam3 - lam4 - lam5) + (-lam1 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ -S[6] , S[4] , S[4] , -S[4] ] == {{(-2*I)*cb*sb*(cb^2*(lam2 - lam3 - lam4 - lam5) + (-lam1 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ S[6] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*cb*sb*(cb^2*(lam2 - lam3 - lam4 - lam5) + (-lam1 + lam3 + lam4 + lam5)*sb^2), 0}},

C[ S[5] , S[5] , S[2] ] == {{(-I)*(sa*sb*(cb^2*(lam3 + lam4 + lam5) + lam2*sb^2) + ca*cb*(cb^2*lam1 + (lam3 + lam4 + lam5)*sb^2))*vev, 0}},

C[ S[6] , -S[6] , S[2] ] == {{(-I)*(sa*sb*(cb^2*(lam3 + lam4 + lam5) + lam2*sb^2) + ca*cb*(cb^2*lam1 + (lam3 + lam4 + lam5)*sb^2))*vev, 0}},

C[ S[2] , S[2] , S[2] ] == {{(-3*I)*(ca^3*cb*lam1 + ca*cb*(lam3 + lam4 + lam5)*sa^2 + ca^2*(lam3 + lam4 + lam5)*sa*sb + lam2*sa^3*sb)*vev, 0}},

C[ S[3] , S[3] , S[2] ] == {{(-I)*(ca*cb*(cb^2*(lam3 + lam4 - lam5) + (lam1 - 2*lam5)*sb^2) + sa*sb*(cb^2*(lam2 - 2*lam5) + (lam3 + lam4 - lam5)*sb^2))*vev, 0}},

C[ S[2] , S[1] , S[1] ] == {{(-I)*(ca^3*cb*(lam3 + lam4 + lam5) + ca*cb*(3*lam1 - 2*(lam3 + lam4 + lam5))*sa^2 + ca^2*(3*lam2 - 2*(lam3 + lam4 + lam5))*sa*sb + (lam3 + lam4 + lam5)*sa^3*sb)*vev, 0}},

C[ S[2] , S[4] , -S[4] ] == {{(-I)*(sa*sb*(cb^2*(lam2 - lam4 - lam5) + lam3*sb^2) + ca*cb*(cb^2*lam3 + (lam1 - lam4 - lam5)*sb^2))*vev, 0}},

C[ -S[6] , S[3] , S[4] ] == {{-((lam4 - lam5)*(cb^2 + sb^2)^2*vev)/2, 0}},

C[ -S[6] , S[1] , S[4] ] == {{(-I/2)*(ca*cb*(cb^2*(lam4 + lam5) + (2*lam2 - 2*lam3 - lam4 - lam5)*sb^2) + sa*sb*(cb^2*(2*lam1 - 2*lam3 - lam4 - lam5) + (lam4 + lam5)*sb^2))*vev, 0}},

C[ S[6] , S[3] , -S[4] ] == {{((lam4 - lam5)*(cb^2 + sb^2)^2*vev)/2, 0}},

C[ S[6] , S[1] , -S[4] ] == {{(-I/2)*(ca*cb*(cb^2*(lam4 + lam5) + (2*lam2 - 2*lam3 - lam4 - lam5)*sb^2) + sa*sb*(cb^2*(2*lam1 - 2*lam3 - lam4 - lam5) + (lam4 + lam5)*sb^2))*vev, 0}},

C[ S[5] , S[3] , S[1] ] == {{(-I)*(ca*cb*(cb^2*lam5 + (lam2 - lam3 - lam4)*sb^2) + sa*sb*(cb^2*(lam1 - lam3 - lam4) + lam5*sb^2))*vev, 0}},

C[ S[5] , S[5] , S[1] ] == {{I*(cb^3*lam1*sa - ca*cb^2*(lam3 + lam4 + lam5)*sb + cb*(lam3 + lam4 + lam5)*sa*sb^2 - ca*lam2*sb^3)*vev, 0}},

C[ S[6] , -S[6] , S[1] ] == {{I*(cb^3*lam1*sa - ca*cb^2*(lam3 + lam4 + lam5)*sb + cb*(lam3 + lam4 + lam5)*sa*sb^2 - ca*lam2*sb^3)*vev, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-I)*(ca^2*cb*(-3*lam1 + 2*(lam3 + lam4 + lam5))*sa - cb*(lam3 + lam4 + lam5)*sa^3 + ca^3*(lam3 + lam4 + lam5)*sb + ca*(3*lam2 - 2*(lam3 + lam4 + lam5))*sa^2*sb)*vev, 0}},

C[ S[3] , S[3] , S[1] ] == {{I*(cb^3*(lam3 + lam4 - lam5)*sa - ca*cb^2*(lam2 - 2*lam5)*sb + cb*(lam1 - 2*lam5)*sa*sb^2 - ca*(lam3 + lam4 - lam5)*sb^3)*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*(-(ca^2*cb*(lam3 + lam4 + lam5)*sa) - cb*lam1*sa^3 + ca^3*lam2*sb + ca*(lam3 + lam4 + lam5)*sa^2*sb)*vev, 0}},

C[ S[1] , S[4] , -S[4] ] == {{I*(cb^3*lam3*sa + ca*cb^2*(-lam2 + lam4 + lam5)*sb + cb*(lam1 - lam4 - lam5)*sa*sb^2 - ca*lam3*sb^3)*vev, 0}},

C[ -S[6] , S[2] , S[4] ] == {{(-I/2)*(cb^3*(lam4 + lam5)*sa + ca*cb^2*(-2*lam1 + 2*lam3 + lam4 + lam5)*sb + cb*(2*lam2 - 2*lam3 - lam4 - lam5)*sa*sb^2 - ca*(lam4 + lam5)*sb^3)*vev, 0}},

C[ S[6] , S[2] , -S[4] ] == {{(-I/2)*(cb^3*(lam4 + lam5)*sa + ca*cb^2*(-2*lam1 + 2*lam3 + lam4 + lam5)*sb + cb*(2*lam2 - 2*lam3 - lam4 - lam5)*sa*sb^2 - ca*(lam4 + lam5)*sb^3)*vev, 0}},

C[ S[5] , S[3] , S[2] ] == {{(-I)*(cb^3*lam5*sa + ca*cb^2*(-lam1 + lam3 + lam4)*sb + cb*(lam2 - lam3 - lam4)*sa*sb^2 - ca*lam5*sb^3)*vev, 0}},

C[ S[6] , -S[6] , V[1] , V[1] ] == {{2*EL^2*(cb + I*sb)*(I*cb + sb), 0}},

C[ S[4] , -S[4] , V[1] , V[1] ] == {{2*EL^2*(cb + I*sb)*(I*cb + sb), 0}},

C[ S[6] , -S[6] , V[1] ] == {{(-I)*gc91, 0}, {I*gc91, 0}},

C[ S[4] , -S[4] , V[1] ] == {{(-I)*gc92, 0}, {I*gc92, 0}},

C[ S[5] , -S[6] , V[1] , V[3] ] == {{-(EL^2*(cb^2 + sb^2))/(2*sw), 0}},

C[ -S[6] , S[2] , V[1] , V[3] ] == {{((I/2)*EL^2*(ca*cb + sa*sb))/sw, 0}},

C[ S[3] , -S[4] , V[1] , V[3] ] == {{-(EL^2*(cb^2 + sb^2))/(2*sw), 0}},

C[ S[1] , -S[4] , V[1] , V[3] ] == {{((I/2)*EL^2*(ca*cb + sa*sb))/sw, 0}},

C[ -S[6] , S[1] , V[1] , V[3] ] == {{((-I/2)*EL^2*(cb*sa - ca*sb))/sw, 0}},

C[ S[2] , -S[4] , V[1] , V[3] ] == {{((I/2)*EL^2*(cb*sa - ca*sb))/sw, 0}},

C[ -S[6] , V[1] , V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*vev)/sw, 0}},

C[ S[5] , -S[6] , V[3] ] == {{-gc100, 0}, {gc100, 0}},

C[ -S[6] , S[2] , V[3] ] == {{(-I)*gc101, 0}, {I*gc101, 0}},

C[ -S[6] , S[1] , V[3] ] == {{(-I)*gc102, 0}, {I*gc102, 0}},

C[ S[3] , -S[4] , V[3] ] == {{-gc103, 0}, {gc103, 0}},

C[ S[2] , -S[4] , V[3] ] == {{(-I)*gc104, 0}, {I*gc104, 0}},

C[ S[1] , -S[4] , V[3] ] == {{(-I)*gc105, 0}, {I*gc105, 0}},

C[ S[5] , S[6] , V[1] , -V[3] ] == {{(EL^2*(cb^2 + sb^2))/(2*sw), 0}},

C[ S[6] , S[2] , V[1] , -V[3] ] == {{((I/2)*EL^2*(ca*cb + sa*sb))/sw, 0}},

C[ S[3] , S[4] , V[1] , -V[3] ] == {{(EL^2*(cb^2 + sb^2))/(2*sw), 0}},

C[ S[1] , S[4] , V[1] , -V[3] ] == {{((I/2)*EL^2*(ca*cb + sa*sb))/sw, 0}},

C[ S[6] , S[1] , V[1] , -V[3] ] == {{((-I/2)*EL^2*(cb*sa - ca*sb))/sw, 0}},

C[ S[2] , S[4] , V[1] , -V[3] ] == {{((I/2)*EL^2*(cb*sa - ca*sb))/sw, 0}},

C[ S[6] , V[1] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*vev)/sw, 0}},

C[ S[5] , S[6] , -V[3] ] == {{-gc113, 0}, {gc113, 0}},

C[ S[6] , S[2] , -V[3] ] == {{(-I)*gc114, 0}, {I*gc114, 0}},

C[ S[6] , S[1] , -V[3] ] == {{(-I)*gc115, 0}, {I*gc115, 0}},

C[ S[3] , S[4] , -V[3] ] == {{-gc116, 0}, {gc116, 0}},

C[ S[2] , S[4] , -V[3] ] == {{(-I)*gc117, 0}, {I*gc117, 0}},

C[ S[1] , S[4] , -V[3] ] == {{(-I)*gc118, 0}, {I*gc118, 0}},

C[ S[5] , S[5] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2))/sw^2, 0}},

C[ S[6] , -S[6] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2))/sw^2, 0}},

C[ S[3] , S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2))/sw^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2*(ca^2 + sa^2))/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*(ca^2 + sa^2))/sw^2, 0}},

C[ S[4] , -S[4] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2))/sw^2, 0}},

C[ S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2*(ca*cb + sa*sb)*vev)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((-I/2)*EL^2*(cb*sa - ca*sb)*vev)/sw^2, 0}},

C[ S[6] , -S[6] , V[1] , V[2] ] == {{(I*EL^2*(cb^2 + sb^2)*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[4] , -S[4] , V[1] , V[2] ] == {{(I*EL^2*(cb^2 + sb^2)*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[5] , S[2] , V[2] ] == {{-gc129, 0}, {gc129, 0}},

C[ S[5] , S[1] , V[2] ] == {{-gc130, 0}, {gc130, 0}},

C[ S[6] , -S[6] , V[2] ] == {{(-I)*gc131, 0}, {I*gc131, 0}},

C[ S[3] , S[1] , V[2] ] == {{-gc132, 0}, {gc132, 0}},

C[ S[3] , S[2] , V[2] ] == {{-gc133, 0}, {gc133, 0}},

C[ S[4] , -S[4] , V[2] ] == {{(-I)*gc134, 0}, {I*gc134, 0}},

C[ S[5] , -S[6] , V[3] , V[2] ] == {{(EL^2*(cb^2 + sb^2))/(2*cw), 0}},

C[ -S[6] , S[2] , V[3] , V[2] ] == {{((-I/2)*EL^2*(ca*cb + sa*sb))/cw, 0}},

C[ S[3] , -S[4] , V[3] , V[2] ] == {{(EL^2*(cb^2 + sb^2))/(2*cw), 0}},

C[ S[1] , -S[4] , V[3] , V[2] ] == {{((-I/2)*EL^2*(ca*cb + sa*sb))/cw, 0}},

C[ -S[6] , S[1] , V[3] , V[2] ] == {{((I/2)*EL^2*(cb*sa - ca*sb))/cw, 0}},

C[ S[2] , -S[4] , V[3] , V[2] ] == {{((-I/2)*EL^2*(cb*sa - ca*sb))/cw, 0}},

C[ -S[6] , V[3] , V[2] ] == {{((-I/2)*EL^2*(cb^2 + sb^2)*vev)/cw, 0}},

C[ S[5] , S[6] , -V[3] , V[2] ] == {{-(EL^2*(cb^2 + sb^2))/(2*cw), 0}},

C[ S[6] , S[2] , -V[3] , V[2] ] == {{((-I/2)*EL^2*(ca*cb + sa*sb))/cw, 0}},

C[ S[3] , S[4] , -V[3] , V[2] ] == {{-(EL^2*(cb^2 + sb^2))/(2*cw), 0}},

C[ S[1] , S[4] , -V[3] , V[2] ] == {{((-I/2)*EL^2*(ca*cb + sa*sb))/cw, 0}},

C[ S[6] , S[1] , -V[3] , V[2] ] == {{((I/2)*EL^2*(cb*sa - ca*sb))/cw, 0}},

C[ S[2] , S[4] , -V[3] , V[2] ] == {{((-I/2)*EL^2*(cb*sa - ca*sb))/cw, 0}},

C[ S[6] , -V[3] , V[2] ] == {{((-I/2)*EL^2*(cb^2 + sb^2)*vev)/cw, 0}},

C[ S[5] , S[5] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[6] , -S[6] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[3] , S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(ca^2 + sa^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(ca^2 + sa^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , -S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(ca*cb + sa*sb)*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((-I/2)*EL^2*(cb*sa - ca*sb)*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc157*IndexDelta[e1x2, e2x2], 0}, {I*gc157*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc158*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc158*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc159*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc159*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc160*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc160*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc161*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc161*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc162[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc163[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc164*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc165*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc166L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc166R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc167L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc167R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc168*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc169L*IndexDelta[e1x2, e2x2], 0}, {I*gc169R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[6] ] == {{I*gc170L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc170R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[4] ] == {{I*gc171L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc171R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[5] ] == {{gc172L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc172R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[2] ] == {{I*gc173L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc173R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc174L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc174R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[3] ] == {{gc175L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc175R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[6] ] == {{I*gc176[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[4] ] == {{I*gc177[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[5] ] == {{gc178L[e1x2, e2x2], 0}, {gc178R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[2] ] == {{I*gc179L[e1x2, e2x2], 0}, {I*gc179R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc180L[e1x2, e2x2], 0}, {I*gc180R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[3] ] == {{gc181L[e1x2, e2x2], 0}, {gc181R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[6] ] == {{I*gc182L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc182R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[4] ] == {{I*gc183L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc183R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[5] ] == {{gc184L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc184R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[3] ] == {{gc185L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc185R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc186L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc186R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{I*gc187L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc187R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[6] ] == {{0, 0}, {I*gc188R[e1x2, e2x2], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[4] ] == {{0, 0}, {I*gc189R[e1x2, e2x2], 0}},

C[ -U[1] , U[32] , V[3] ] == {{I*gc190, 0}, {I*gc190, 0}, {0, 0}},

C[ -U[1] , U[31] , -V[3] ] == {{I*gc191, 0}, {I*gc191, 0}, {0, 0}},

C[ -S[6] , -U[32] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[32] , U[1] , -V[3] ] == {{I*gc193, 0}, {I*gc193, 0}, {0, 0}},

C[ -U[32] , U[32] , V[1] ] == {{I*gc194, 0}, {I*gc194, 0}, {0, 0}},

C[ -U[32] , U[32] , V[2] ] == {{I*gc195, 0}, {I*gc195, 0}, {0, 0}},

C[ -S[6] , -U[32] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[32] , U[2] , -V[3] ] == {{I*gc197, 0}, {I*gc197, 0}, {0, 0}},

C[ S[6] , -U[31] , U[1] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ -U[31] , U[1] , V[3] ] == {{I*gc199, 0}, {I*gc199, 0}, {0, 0}},

C[ -U[31] , U[31] , V[1] ] == {{I*gc200, 0}, {I*gc200, 0}, {0, 0}},

C[ -U[31] , U[31] , V[2] ] == {{I*gc201, 0}, {I*gc201, 0}, {0, 0}},

C[ S[6] , -U[31] , U[2] ] == {{-(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[31] , U[2] , V[3] ] == {{I*gc203, 0}, {I*gc203, 0}, {0, 0}},

C[ S[6] , -U[2] , U[32] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[32] , V[3] ] == {{I*gc205, 0}, {I*gc205, 0}, {0, 0}},

C[ -S[6] , -U[2] , U[31] ] == {{-(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[31] , -V[3] ] == {{I*gc207, 0}, {I*gc207, 0}, {0, 0}},

C[ -U[4, {e1x1}] , U[4, {e2x1}] , V[4, {e3x2}] ] == {{gc208*SUNF[e3x2, e1x1, e2x1], 0}, {gc208*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -GS,
     gc2 -> -GS^2,
     gc3 -> EL,
     gc4 -> -EL^2,
     gc5 -> (cw*EL)/sw,
     gc6 -> EL^2/sw^2,
     gc7 -> (cw*EL^2)/sw,
     gc8 -> -((cw^2*EL^2)/sw^2),
     gc91 -> -(EL*(cb^2 + sb^2)),
     gc92 -> -(EL*(cb^2 + sb^2)),
     gc100 -> (EL*(cb^2 + sb^2))/(2*sw),
     gc101 -> (EL*(ca*cb + sa*sb))/(2*sw),
     gc102 -> -(EL*(cb*sa - ca*sb))/(2*sw),
     gc103 -> (EL*(cb^2 + sb^2))/(2*sw),
     gc104 -> -(EL*(cb*sa - ca*sb))/(2*sw),
     gc105 -> -(EL*(ca*cb + sa*sb))/(2*sw),
     gc113 -> (EL*(cb^2 + sb^2))/(2*sw),
     gc114 -> -(EL*(ca*cb + sa*sb))/(2*sw),
     gc115 -> (EL*(cb*sa - ca*sb))/(2*sw),
     gc116 -> (EL*(cb^2 + sb^2))/(2*sw),
     gc117 -> (EL*(cb*sa - ca*sb))/(2*sw),
     gc118 -> (EL*(ca*cb + sa*sb))/(2*sw),
     gc129 -> -(EL*(ca*cb + sa*sb)*(cw^2 + sw^2))/(2*cw*sw),
     gc130 -> (EL*(cb*sa - ca*sb)*(cw^2 + sw^2))/(2*cw*sw),
     gc131 -> -(EL*(cb^2 + sb^2)*(cw^2 - sw^2))/(2*cw*sw),
     gc132 -> -(EL*(ca*cb + sa*sb)*(cw^2 + sw^2))/(2*cw*sw),
     gc133 -> -(EL*(cb*sa - ca*sb)*(cw^2 + sw^2))/(2*cw*sw),
     gc134 -> -(EL*(cb^2 + sb^2)*(cw^2 - sw^2))/(2*cw*sw),
     gc157 -> -EL,
     gc158 -> (2*EL)/3,
     gc159 -> -EL/3,
     gc160 -> GS,
     gc161 -> GS,
     gc162[e1x2_, e2x2_] -> (EL*CKM[e1x2, e2x2])/(Sqrt[2]*sw),
     gc163[e1x2_, e2x2_] -> (EL*Conjugate[CKM[e2x2, e1x2]])/(Sqrt[2]*sw),
     gc164 -> EL/(Sqrt[2]*sw),
     gc165 -> EL/(Sqrt[2]*sw),
     gc166L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc166R -> (-2*EL*sw)/(3*cw),
     gc167L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc167R -> (EL*sw)/(3*cw),
     gc168 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc169L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc169R -> (EL*sw)/cw,
     gc170L[e1x2_, e2x2_] -> -IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[yd[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc170R[e1x2_, e2x2_] -> IndexSum[Conjugate[CKM[Generation$1, e1x2]]*yu[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc171L[e1x2_, e2x2_] -> (sb*IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[yd[Generation$1, e1x2]], {Generation$1, 1, 3}])/cb,
     gc171R[e1x2_, e2x2_] -> (cb*IndexSum[Conjugate[CKM[Generation$1, e1x2]]*yu[Generation$1, e2x2], {Generation$1, 1, 3}])/sb,
     gc172L[e1x2_, e2x2_] -> -(Conjugate[yd[e2x2, e1x2]]/Sqrt[2]),
     gc172R[e1x2_, e2x2_] -> yd[e1x2, e2x2]/Sqrt[2],
     gc173L[e1x2_, e2x2_] -> -((ca*Conjugate[yd[e2x2, e1x2]])/(Sqrt[2]*cb)),
     gc173R[e1x2_, e2x2_] -> -((ca*yd[e1x2, e2x2])/(Sqrt[2]*cb)),
     gc174L[e1x2_, e2x2_] -> (sa*Conjugate[yd[e2x2, e1x2]])/(Sqrt[2]*cb),
     gc174R[e1x2_, e2x2_] -> (sa*yd[e1x2, e2x2])/(Sqrt[2]*cb),
     gc175L[e1x2_, e2x2_] -> (sb*Conjugate[yd[e2x2, e1x2]])/(Sqrt[2]*cb),
     gc175R[e1x2_, e2x2_] -> -((sb*yd[e1x2, e2x2])/(Sqrt[2]*cb)),
     gc176[e1x2_, e2x2_] -> -Conjugate[yl[e2x2, e1x2]],
     gc177[e1x2_, e2x2_] -> (sb*Conjugate[yl[e2x2, e1x2]])/cb,
     gc178L[e1x2_, e2x2_] -> -(Conjugate[yl[e2x2, e1x2]]/Sqrt[2]),
     gc178R[e1x2_, e2x2_] -> yl[e1x2, e2x2]/Sqrt[2],
     gc179L[e1x2_, e2x2_] -> -((ca*Conjugate[yl[e2x2, e1x2]])/(Sqrt[2]*cb)),
     gc179R[e1x2_, e2x2_] -> -((ca*yl[e1x2, e2x2])/(Sqrt[2]*cb)),
     gc180L[e1x2_, e2x2_] -> (sa*Conjugate[yl[e2x2, e1x2]])/(Sqrt[2]*cb),
     gc180R[e1x2_, e2x2_] -> (sa*yl[e1x2, e2x2])/(Sqrt[2]*cb),
     gc181L[e1x2_, e2x2_] -> (sb*Conjugate[yl[e2x2, e1x2]])/(Sqrt[2]*cb),
     gc181R[e1x2_, e2x2_] -> -((sb*yl[e1x2, e2x2])/(Sqrt[2]*cb)),
     gc182L[e1x2_, e2x2_] -> IndexSum[CKM[Generation$1, e2x2]*Conjugate[yu[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc182R[e1x2_, e2x2_] -> -IndexSum[CKM[e1x2, Generation$1]*yd[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc183L[e1x2_, e2x2_] -> (cb*IndexSum[CKM[Generation$1, e2x2]*Conjugate[yu[Generation$1, e1x2]], {Generation$1, 1, 3}])/sb,
     gc183R[e1x2_, e2x2_] -> (sb*IndexSum[CKM[e1x2, Generation$1]*yd[Generation$1, e2x2], {Generation$1, 1, 3}])/cb,
     gc184L[e1x2_, e2x2_] -> Conjugate[yu[e2x2, e1x2]]/Sqrt[2],
     gc184R[e1x2_, e2x2_] -> -(yu[e1x2, e2x2]/Sqrt[2]),
     gc185L[e1x2_, e2x2_] -> (cb*Conjugate[yu[e2x2, e1x2]])/(Sqrt[2]*sb),
     gc185R[e1x2_, e2x2_] -> -((cb*yu[e1x2, e2x2])/(Sqrt[2]*sb)),
     gc186L[e1x2_, e2x2_] -> -((ca*Conjugate[yu[e2x2, e1x2]])/(Sqrt[2]*sb)),
     gc186R[e1x2_, e2x2_] -> -((ca*yu[e1x2, e2x2])/(Sqrt[2]*sb)),
     gc187L[e1x2_, e2x2_] -> -((sa*Conjugate[yu[e2x2, e1x2]])/(Sqrt[2]*sb)),
     gc187R[e1x2_, e2x2_] -> -((sa*yu[e1x2, e2x2])/(Sqrt[2]*sb)),
     gc188R[e1x2_, e2x2_] -> -yl[e1x2, e2x2],
     gc189R[e1x2_, e2x2_] -> (sb*yl[e1x2, e2x2])/cb,
     gc190 -> EL,
     gc191 -> -EL,
     gc193 -> EL,
     gc194 -> -EL,
     gc195 -> -((cw*EL)/sw),
     gc197 -> (cw*EL)/sw,
     gc199 -> -EL,
     gc200 -> EL,
     gc201 -> (cw*EL)/sw,
     gc203 -> -((cw*EL)/sw),
     gc205 -> (cw*EL)/sw,
     gc207 -> -((cw*EL)/sw),
     gc208 -> GS};

