(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"2HDM CPC",
  Authors -> {"Yongcheng Wu"},
  Version -> "0.1.2",
  Date -> "01. 09. 2019",
  Institutions -> {"Carleton University"},
  Emails -> {"ycwu@physics.carleton.ca"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[5], S[6]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HL",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHL,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HH",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHH,
    Indices -> {} },

S[3] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HA",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHA,
    Indices -> {} },

S[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "Hpm",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHp,
    Indices -> {} },

S[5] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = 1;
GaugeXi[ S[3] ] = 1;
GaugeXi[ S[4] ] = 1;
GaugeXi[ S[5] ] = GaugeXi[Z];
GaugeXi[ S[6] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MHL[ ___ ] := MHL;
MHH[ ___ ] := MHH;
MHA[ ___ ] := MHA;
MHp[ ___ ] := MHp;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc1*SUNF[e1x2, e2x2, e3x2]), 0}, {gc1*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc3, 0}, {I*gc3, 0}, {I*gc3, 0}, {(-I)*gc3, 0}, {(-I)*gc3, 0}, {I*gc3, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc4, 0}, {(-I)*gc4, 0}, {(2*I)*gc4, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc5, 0}, {I*gc5, 0}, {I*gc5, 0}, {(-I)*gc5, 0}, {(-I)*gc5, 0}, {I*gc5, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc6, 0}, {(-I)*gc6, 0}, {(2*I)*gc6, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc7, 0}, {I*gc7, 0}, {I*gc7, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc8, 0}, {(-I)*gc8, 0}, {(2*I)*gc8, 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-3*I)*(ca^4*lam1 + 2*ca^2*(lam3 + lam4 + lam5)*sa^2 + lam2*sa^4), 0}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{(-3*I)*(cb^4*lam2 + 2*cb^2*(lam3 + lam4 + lam5)*sb^2 + lam1*sb^4), 0}},

C[ S[3] , S[3] , S[1] , S[1] ] == {{(-I)*(4*ca*cb*lam5*sa*sb + sa^2*(cb^2*(lam3 + lam4 - lam5) + lam1*sb^2) + ca^2*(cb^2*lam2 + (lam3 + lam4 - lam5)*sb^2)), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-3*I)*(ca^4*lam2 + 2*ca^2*(lam3 + lam4 + lam5)*sa^2 + lam1*sa^4), 0}},

C[ S[3] , S[3] , S[4] , -S[4] ] == {{(-I)*(cb^4*lam2 + 2*cb^2*(lam3 + lam4 + lam5)*sb^2 + lam1*sb^4), 0}},

C[ S[1] , S[1] , S[4] , -S[4] ] == {{(-I)*(2*ca*cb*(lam4 + lam5)*sa*sb + sa^2*(cb^2*lam3 + lam1*sb^2) + ca^2*(cb^2*lam2 + lam3*sb^2)), 0}},

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{(-2*I)*(cb^4*lam2 + 2*cb^2*(lam3 + lam4 + lam5)*sb^2 + lam1*sb^4), 0}},

C[ S[3] , S[3] , S[2] , S[2] ] == {{(-I)*(-4*ca*cb*lam5*sa*sb + ca^2*(cb^2*(lam3 + lam4 - lam5) + lam1*sb^2) + sa^2*(cb^2*lam2 + (lam3 + lam4 - lam5)*sb^2)), 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-I)*(ca^4*(lam3 + lam4 + lam5) + ca^2*(3*lam1 + 3*lam2 - 4*(lam3 + lam4 + lam5))*sa^2 + (lam3 + lam4 + lam5)*sa^4), 0}},

C[ S[2] , S[2] , S[4] , -S[4] ] == {{(-I)*(-2*ca*cb*(lam4 + lam5)*sa*sb + ca^2*(cb^2*lam3 + lam1*sb^2) + sa^2*(cb^2*lam2 + lam3*sb^2)), 0}},

C[ S[2] , S[2] , S[2] , S[1] ] == {{(3*I)*ca*sa*(ca^2*(lam1 - lam3 - lam4 - lam5) + (-lam2 + lam3 + lam4 + lam5)*sa^2), 0}},

C[ S[3] , S[3] , S[2] , S[1] ] == {{I*(2*ca^2*cb*lam5*sb - 2*cb*lam5*sa^2*sb + ca*sa*(cb^2*(-lam2 + lam3 + lam4 - lam5) + (lam1 - lam3 - lam4 + lam5)*sb^2)), 0}},

C[ S[2] , S[1] , S[1] , S[1] ] == {{(-3*I)*ca*sa*(ca^2*(lam2 - lam3 - lam4 - lam5) + (-lam1 + lam3 + lam4 + lam5)*sa^2), 0}},

C[ S[2] , S[1] , S[4] , -S[4] ] == {{I*(ca^2*cb*(lam4 + lam5)*sb - cb*(lam4 + lam5)*sa^2*sb + ca*sa*(cb^2*(-lam2 + lam3) + (lam1 - lam3)*sb^2)), 0}},

C[ S[2] , S[2] , S[2] ] == {{(-3*I)*(ca^3*cb*lam1 + ca*cb*(lam3 + lam4 + lam5)*sa^2 + ca^2*(lam3 + lam4 + lam5)*sa*sb + lam2*sa^3*sb)*vev, 0}},

C[ S[3] , S[3] , S[2] ] == {{(-I)*(ca*cb*(cb^2*(lam3 + lam4 - lam5) + (lam1 - 2*lam5)*sb^2) + sa*sb*(cb^2*(lam2 - 2*lam5) + (lam3 + lam4 - lam5)*sb^2))*vev, 0}},

C[ S[2] , S[1] , S[1] ] == {{(-I)*(ca^3*cb*(lam3 + lam4 + lam5) + ca*cb*(3*lam1 - 2*(lam3 + lam4 + lam5))*sa^2 + ca^2*(3*lam2 - 2*(lam3 + lam4 + lam5))*sa*sb + (lam3 + lam4 + lam5)*sa^3*sb)*vev, 0}},

C[ S[2] , S[4] , -S[4] ] == {{(-I)*(sa*sb*(cb^2*(lam2 - lam4 - lam5) + lam3*sb^2) + ca*cb*(cb^2*lam3 + (lam1 - lam4 - lam5)*sb^2))*vev, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-I)*(ca^2*cb*(-3*lam1 + 2*(lam3 + lam4 + lam5))*sa - cb*(lam3 + lam4 + lam5)*sa^3 + ca^3*(lam3 + lam4 + lam5)*sb + ca*(3*lam2 - 2*(lam3 + lam4 + lam5))*sa^2*sb)*vev, 0}},

C[ S[3] , S[3] , S[1] ] == {{I*(cb^3*(lam3 + lam4 - lam5)*sa - ca*cb^2*(lam2 - 2*lam5)*sb + cb*(lam1 - 2*lam5)*sa*sb^2 - ca*(lam3 + lam4 - lam5)*sb^3)*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*(-(ca^2*cb*(lam3 + lam4 + lam5)*sa) - cb*lam1*sa^3 + ca^3*lam2*sb + ca*(lam3 + lam4 + lam5)*sa^2*sb)*vev, 0}},

C[ S[1] , S[4] , -S[4] ] == {{I*(cb^3*lam3*sa + ca*cb^2*(-lam2 + lam4 + lam5)*sb + cb*(lam1 - lam4 - lam5)*sa*sb^2 - ca*lam3*sb^3)*vev, 0}},

C[ S[4] , -S[4] , V[1] , V[1] ] == {{2*EL^2*(cb + I*sb)*(I*cb + sb), 0}},

C[ S[4] , -S[4] , V[1] ] == {{(-I)*gc32, 0}, {I*gc32, 0}},

C[ S[3] , -S[4] , V[1] , V[3] ] == {{-(EL^2*(cb^2 + sb^2))/(2*sw), 0}},

C[ S[1] , -S[4] , V[1] , V[3] ] == {{((I/2)*EL^2*(ca*cb + sa*sb))/sw, 0}},

C[ S[2] , -S[4] , V[1] , V[3] ] == {{((I/2)*EL^2*(cb*sa - ca*sb))/sw, 0}},

C[ S[3] , -S[4] , V[3] ] == {{-gc36, 0}, {gc36, 0}},

C[ S[2] , -S[4] , V[3] ] == {{(-I)*gc37, 0}, {I*gc37, 0}},

C[ S[1] , -S[4] , V[3] ] == {{(-I)*gc38, 0}, {I*gc38, 0}},

C[ S[3] , S[4] , V[1] , -V[3] ] == {{(EL^2*(cb^2 + sb^2))/(2*sw), 0}},

C[ S[1] , S[4] , V[1] , -V[3] ] == {{((I/2)*EL^2*(ca*cb + sa*sb))/sw, 0}},

C[ S[2] , S[4] , V[1] , -V[3] ] == {{((I/2)*EL^2*(cb*sa - ca*sb))/sw, 0}},

C[ S[3] , S[4] , -V[3] ] == {{-gc42, 0}, {gc42, 0}},

C[ S[2] , S[4] , -V[3] ] == {{(-I)*gc43, 0}, {I*gc43, 0}},

C[ S[1] , S[4] , -V[3] ] == {{(-I)*gc44, 0}, {I*gc44, 0}},

C[ S[3] , S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2))/sw^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2*(ca^2 + sa^2))/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*(ca^2 + sa^2))/sw^2, 0}},

C[ S[4] , -S[4] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2))/sw^2, 0}},

C[ S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2*(ca*cb + sa*sb)*vev)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((-I/2)*EL^2*(cb*sa - ca*sb)*vev)/sw^2, 0}},

C[ S[4] , -S[4] , V[1] , V[2] ] == {{(I*EL^2*(cb^2 + sb^2)*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[3] , S[1] , V[2] ] == {{-gc52, 0}, {gc52, 0}},

C[ S[3] , S[2] , V[2] ] == {{-gc53, 0}, {gc53, 0}},

C[ S[4] , -S[4] , V[2] ] == {{(-I)*gc54, 0}, {I*gc54, 0}},

C[ S[3] , -S[4] , V[3] , V[2] ] == {{(EL^2*(cb^2 + sb^2))/(2*cw), 0}},

C[ S[1] , -S[4] , V[3] , V[2] ] == {{((-I/2)*EL^2*(ca*cb + sa*sb))/cw, 0}},

C[ S[2] , -S[4] , V[3] , V[2] ] == {{((-I/2)*EL^2*(cb*sa - ca*sb))/cw, 0}},

C[ S[3] , S[4] , -V[3] , V[2] ] == {{-(EL^2*(cb^2 + sb^2))/(2*cw), 0}},

C[ S[1] , S[4] , -V[3] , V[2] ] == {{((-I/2)*EL^2*(ca*cb + sa*sb))/cw, 0}},

C[ S[2] , S[4] , -V[3] , V[2] ] == {{((-I/2)*EL^2*(cb*sa - ca*sb))/cw, 0}},

C[ S[3] , S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(ca^2 + sa^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(ca^2 + sa^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , -S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(ca*cb + sa*sb)*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((-I/2)*EL^2*(cb*sa - ca*sb)*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc67*IndexDelta[e1x2, e2x2], 0}, {I*gc67*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc68*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc68*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc69*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc69*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc70*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc70*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc71*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc71*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc72[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc73[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc74*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc75*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc76L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc76R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc77L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc77R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc78*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc79L*IndexDelta[e1x2, e2x2], 0}, {I*gc79R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[4] ] == {{I*gc80L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc80R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[2] ] == {{I*gc81L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc81R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc82L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc82R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[3] ] == {{gc83L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc83R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[4] ] == {{I*gc84[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[2] ] == {{I*gc85L[e1x2, e2x2], 0}, {I*gc85R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc86L[e1x2, e2x2], 0}, {I*gc86R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[3] ] == {{gc87L[e1x2, e2x2], 0}, {gc87R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[4] ] == {{I*gc88L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc88R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[3] ] == {{gc89L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc89R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc90L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc90R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{I*gc91L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc91R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[4] ] == {{0, 0}, {I*gc92R[e1x2, e2x2], 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -GS,
     gc2 -> -GS^2,
     gc3 -> EL,
     gc4 -> -EL^2,
     gc5 -> (cw*EL)/sw,
     gc6 -> EL^2/sw^2,
     gc7 -> (cw*EL^2)/sw,
     gc8 -> -((cw^2*EL^2)/sw^2),
     gc32 -> -(EL*(cb^2 + sb^2)),
     gc36 -> (EL*(cb^2 + sb^2))/(2*sw),
     gc37 -> -(EL*(cb*sa - ca*sb))/(2*sw),
     gc38 -> -(EL*(ca*cb + sa*sb))/(2*sw),
     gc42 -> (EL*(cb^2 + sb^2))/(2*sw),
     gc43 -> (EL*(cb*sa - ca*sb))/(2*sw),
     gc44 -> (EL*(ca*cb + sa*sb))/(2*sw),
     gc52 -> -(EL*(ca*cb + sa*sb)*(cw^2 + sw^2))/(2*cw*sw),
     gc53 -> -(EL*(cb*sa - ca*sb)*(cw^2 + sw^2))/(2*cw*sw),
     gc54 -> -(EL*(cb^2 + sb^2)*(cw^2 - sw^2))/(2*cw*sw),
     gc67 -> -EL,
     gc68 -> (2*EL)/3,
     gc69 -> -EL/3,
     gc70 -> GS,
     gc71 -> GS,
     gc72[e1x2_, e2x2_] -> (EL*CKM[e1x2, e2x2])/(Sqrt[2]*sw),
     gc73[e1x2_, e2x2_] -> (EL*Conjugate[CKM[e2x2, e1x2]])/(Sqrt[2]*sw),
     gc74 -> EL/(Sqrt[2]*sw),
     gc75 -> EL/(Sqrt[2]*sw),
     gc76L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc76R -> (-2*EL*sw)/(3*cw),
     gc77L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc77R -> (EL*sw)/(3*cw),
     gc78 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc79L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc79R -> (EL*sw)/cw,
     gc80L[e1x2_, e2x2_] -> (sb*IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[yd[Generation$1, e1x2]], {Generation$1, 1, 3}])/cb,
     gc80R[e1x2_, e2x2_] -> (cb*IndexSum[Conjugate[CKM[Generation$1, e1x2]]*yu[Generation$1, e2x2], {Generation$1, 1, 3}])/sb,
     gc81L[e1x2_, e2x2_] -> -((ca*Conjugate[yd[e2x2, e1x2]])/(Sqrt[2]*cb)),
     gc81R[e1x2_, e2x2_] -> -((ca*yd[e1x2, e2x2])/(Sqrt[2]*cb)),
     gc82L[e1x2_, e2x2_] -> (sa*Conjugate[yd[e2x2, e1x2]])/(Sqrt[2]*cb),
     gc82R[e1x2_, e2x2_] -> (sa*yd[e1x2, e2x2])/(Sqrt[2]*cb),
     gc83L[e1x2_, e2x2_] -> (sb*Conjugate[yd[e2x2, e1x2]])/(Sqrt[2]*cb),
     gc83R[e1x2_, e2x2_] -> -((sb*yd[e1x2, e2x2])/(Sqrt[2]*cb)),
     gc84[e1x2_, e2x2_] -> (sb*Conjugate[yl[e2x2, e1x2]])/cb,
     gc85L[e1x2_, e2x2_] -> -((ca*Conjugate[yl[e2x2, e1x2]])/(Sqrt[2]*cb)),
     gc85R[e1x2_, e2x2_] -> -((ca*yl[e1x2, e2x2])/(Sqrt[2]*cb)),
     gc86L[e1x2_, e2x2_] -> (sa*Conjugate[yl[e2x2, e1x2]])/(Sqrt[2]*cb),
     gc86R[e1x2_, e2x2_] -> (sa*yl[e1x2, e2x2])/(Sqrt[2]*cb),
     gc87L[e1x2_, e2x2_] -> (sb*Conjugate[yl[e2x2, e1x2]])/(Sqrt[2]*cb),
     gc87R[e1x2_, e2x2_] -> -((sb*yl[e1x2, e2x2])/(Sqrt[2]*cb)),
     gc88L[e1x2_, e2x2_] -> (cb*IndexSum[CKM[Generation$1, e2x2]*Conjugate[yu[Generation$1, e1x2]], {Generation$1, 1, 3}])/sb,
     gc88R[e1x2_, e2x2_] -> (sb*IndexSum[CKM[e1x2, Generation$1]*yd[Generation$1, e2x2], {Generation$1, 1, 3}])/cb,
     gc89L[e1x2_, e2x2_] -> (cb*Conjugate[yu[e2x2, e1x2]])/(Sqrt[2]*sb),
     gc89R[e1x2_, e2x2_] -> -((cb*yu[e1x2, e2x2])/(Sqrt[2]*sb)),
     gc90L[e1x2_, e2x2_] -> -((ca*Conjugate[yu[e2x2, e1x2]])/(Sqrt[2]*sb)),
     gc90R[e1x2_, e2x2_] -> -((ca*yu[e1x2, e2x2])/(Sqrt[2]*sb)),
     gc91L[e1x2_, e2x2_] -> -((sa*Conjugate[yu[e2x2, e1x2]])/(Sqrt[2]*sb)),
     gc91R[e1x2_, e2x2_] -> -((sa*yu[e1x2, e2x2])/(Sqrt[2]*sb)),
     gc92R[e1x2_, e2x2_] -> (sb*yl[e1x2, e2x2])/cb};

