(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"2HDM CPC",
  Authors -> {"Yongcheng Wu"},
  Version -> "0.6.0",
  Date -> "04. 09. 2025",
  Institutions -> {"Nanjing Normal University"},
  Emails -> {"ycwu0830@gmail.com"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[5], S[6]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HL",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHL,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HH",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHH,
    Indices -> {} },

S[3] == {
    SelfConjugate -> True,
    PropagatorLabel -> "HA",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHA,
    Indices -> {} },

S[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "Hpm",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MHp,
    Indices -> {} },

S[5] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = 1;
GaugeXi[ S[3] ] = 1;
GaugeXi[ S[4] ] = 1;
GaugeXi[ S[5] ] = GaugeXi[Z];
GaugeXi[ S[6] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MHL[ ___ ] := MHL;
MHH[ ___ ] := MHH;
MHA[ ___ ] := MHA;
MHp[ ___ ] := MHp;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(GS*SUNF[e1x2, e2x2, e3x2]), 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}},

C[ V[1] , V[3] , -V[3] ] == {{I*EL, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-2*I)*gc4, 0}, {I*gc4, 0}, {I*gc4, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(I*cw*EL)/sw, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-2*I)*gc6, 0}, {I*gc6, 0}, {I*gc6, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-I)*gc7, 0}, {(-I)*gc7, 0}, {(2*I)*gc7, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-2*I)*gc8, 0}, {I*gc8, 0}, {I*gc8, 0}},

C[ S[5] , S[3] , S[3] , S[3] ] == {{((-3*I)*(cb^3*cba^2*(MHH^2 - MHL^2)*sb^5 + m122*sb^6 + cb*(-(cba^2*MHL^2*sb^7) + MHH^2*sb^5*(-1 + cba^2*sb^2)) + cb^7*(MHH^2 - MHL^2)*sb*sba^2 - cb^6*(m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) - cb^4*sb^2*(m122 + 2*cba*(MHH^2 - MHL^2)*sb^2*sba) + cb^2*sb^4*(m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^5*(MHH^2*sb^3*sba^2 + MHL^2*(sb - sb^3*sba^2))))/(cb^2*sb^2*vev^2), 0}},

C[ S[3] , S[3] , S[2] , S[1] ] == {{(I*(-(cba*m122*sb^8*sba) + cb^9*cba*(MHH^2 - MHL^2)*sb*sba^3 + cb*sb^7*(-(cba^2*m122) + cba*MHH^2*sba + cba^3*(-MHH^2 + MHL^2)*sb^2*sba + m122*sba^2) + cb^4*cba*sb^4*(cba^3*(-MHH^2 + MHL^2)*sb^2 + 6*m122*sba + 2*cba*(MHH^2 - MHL^2)*sb^2*sba^2) - cb^8*sba*(cba*m122 + 2*cba^2*(MHH^2 - MHL^2)*sb^2*sba + (-MHH^2 + MHL^2)*sb^2*sba^3) - cb^5*sb^3*(-(cba^2*m122) + 3*cba^3*(-MHH^2 + MHL^2)*sb^2*sba + m122*sba^2 + cba*sba*(sb^2*(4*MHA^2 + 3*MHH^2*sba^2) + MHL^2*(1 - 3*sb^2*sba^2))) + cb^3*sb^5*(-(cba^2*m122) + cba^3*(MHH^2 - MHL^2)*sb^2*sba + m122*sba^2 - cba*sba*(sb^2*(2*MHA^2 - MHL^2*sba^2) + MHH^2*(1 + sb^2*sba^2))) + cb^7*sb*(cba^2*m122 + cba^3*(MHH^2 - MHL^2)*sb^2*sba - m122*sba^2 + cba*sba*(-(sb^2*(2*MHA^2 + MHH^2*sba^2)) + MHL^2*(1 + sb^2*sba^2))) + cb^6*sb^2*(2*cba*m122*sba + MHH^2*sb^2*sba^4 + MHL^2*(sba^2 - sb^2*sba^4) + cba^2*(-2*MHH^2*sb^2*sba^2 + MHL^2*(-1 + 2*sb^2*sba^2))) + cb^2*sb^6*(cba^4*(-MHH^2 + MHL^2)*sb^2 + 2*cba*m122*sba - MHH^2*sba^2 + cba^2*(-2*MHL^2*sb^2*sba^2 + MHH^2*(1 + 2*sb^2*sba^2)))))/(cb^3*sb^3*vev^2), 0}},

C[ S[5] , S[3] , S[1] , S[1] ] == {{((-I)*(cba^2*m122*sb^6 + cb*(-(cba^2*MHH^2*sb^5) + cba^4*(MHH^2 - MHL^2)*sb^7) + cb^7*cba^2*(MHH^2 - MHL^2)*sb*sba^2 + cb^4*cba*sb^2*(-(cba*m122) + 4*cba^2*(-MHH^2 + MHL^2)*sb^2*sba + 2*(MHL^2 - 2*MHA^2*sb^2)*sba) + cb^3*(MHH^2 - MHL^2)*sb^3*(cba^4*sb^2 - sba^2 + cba^2*sb^2*sba^2 + sb^2*sba^4) - cb^6*cba*(cba*m122 + cba^2*(MHH^2 - MHL^2)*sb^2*sba + sb^2*sba*(2*MHA^2 + (-MHH^2 + MHL^2)*sba^2)) + cb^2*cba*sb^4*(cba*m122 + 3*cba^2*(-MHH^2 + MHL^2)*sb^2*sba + sb^2*sba*(-2*MHA^2 + MHL^2*sba^2) + MHH^2*(2*sba - sb^2*sba^3)) + cb^5*((MHH^2 - MHL^2)*sb^3*sba^4 + cba^2*(2*MHH^2*sb^3*sba^2 + MHL^2*(sb - 2*sb^3*sba^2)))))/(cb^2*sb^2*vev^2), 0}},

C[ S[2] , S[1] , S[1] , S[1] ] == {{((3*I)*(cba*sb - cb*sba)*(cb*cba + sb*sba)*(-(cba^2*m122*sb^6) + cb^7*cba^2*(-MHH^2 + MHL^2)*sb*sba^2 + cb*cba*sb^5*(cba*MHH^2 + cba^3*(-MHH^2 + MHL^2)*sb^2 + 2*m122*sba) + cb^4*cba*sb^2*(cba*m122 - 2*MHL^2*sba + 4*cba^2*(MHH^2 - MHL^2)*sb^2*sba) + cb^6*cba*(cba*m122 + cba^2*(MHH^2 - MHL^2)*sb^2*sba + (-MHH^2 + MHL^2)*sb^2*sba^3) + cb^2*cba*sb^4*(-(cba*m122) + 3*cba^2*(MHH^2 - MHL^2)*sb^2*sba - MHL^2*sb^2*sba^3 + MHH^2*sba*(-2 + sb^2*sba^2)) + cb^3*sb^3*(cba^4*(-MHH^2 + MHL^2)*sb^2 + 4*cba*m122*sba + cba^2*(-MHH^2 + MHL^2)*sb^2*sba^2 - (MHH^2 - MHL^2)*sba^2*(-1 + sb^2*sba^2)) + cb^5*sb*(2*cba*m122*sba + (-MHH^2 + MHL^2)*sb^2*sba^4 + cba^2*(-2*MHH^2*sb^2*sba^2 + MHL^2*(-1 + 2*sb^2*sba^2)))))/(cb^3*sb^3*vev^2), 0}},

C[ -S[6] , S[3] , S[3] , S[4] ] == {{((-I)*(cb^3*cba^2*(MHH^2 - MHL^2)*sb^5 + m122*sb^6 + cb*(-(cba^2*MHL^2*sb^7) + MHH^2*sb^5*(-1 + cba^2*sb^2)) + cb^7*(MHH^2 - MHL^2)*sb*sba^2 - cb^6*(m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) - cb^4*sb^2*(m122 + 2*cba*(MHH^2 - MHL^2)*sb^2*sba) + cb^2*sb^4*(m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^5*(MHH^2*sb^3*sba^2 + MHL^2*(sb - sb^3*sba^2))))/(cb^2*sb^2*vev^2), 0}},

C[ -S[6] , S[1] , S[1] , S[4] ] == {{((-I)*(cba^2*m122*sb^6 + cb*(-(cba^2*MHH^2*sb^5) + cba^4*(MHH^2 - MHL^2)*sb^7) + cb^7*cba^2*(MHH^2 - MHL^2)*sb*sba^2 + cb^4*cba*sb^2*(-(cba*m122) + 4*cba^2*(-MHH^2 + MHL^2)*sb^2*sba + 2*(MHL^2 - 2*MHp^2*sb^2)*sba) + cb^3*(MHH^2 - MHL^2)*sb^3*(cba^4*sb^2 - sba^2 + cba^2*sb^2*sba^2 + sb^2*sba^4) - cb^6*cba*(cba*m122 + cba^2*(MHH^2 - MHL^2)*sb^2*sba + sb^2*sba*(2*MHp^2 + (-MHH^2 + MHL^2)*sba^2)) + cb^2*cba*sb^4*(cba*m122 + 3*cba^2*(-MHH^2 + MHL^2)*sb^2*sba + sb^2*sba*(-2*MHp^2 + MHL^2*sba^2) + MHH^2*(2*sba - sb^2*sba^3)) + cb^5*((MHH^2 - MHL^2)*sb^3*sba^4 + cba^2*(2*MHH^2*sb^3*sba^2 + MHL^2*(sb - 2*sb^3*sba^2)))))/(cb^2*sb^2*vev^2), 0}},

C[ S[6] , S[3] , S[3] , -S[4] ] == {{((-I)*(cb^3*cba^2*(MHH^2 - MHL^2)*sb^5 + m122*sb^6 + cb*(-(cba^2*MHL^2*sb^7) + MHH^2*sb^5*(-1 + cba^2*sb^2)) + cb^7*(MHH^2 - MHL^2)*sb*sba^2 - cb^6*(m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) - cb^4*sb^2*(m122 + 2*cba*(MHH^2 - MHL^2)*sb^2*sba) + cb^2*sb^4*(m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^5*(MHH^2*sb^3*sba^2 + MHL^2*(sb - sb^3*sba^2))))/(cb^2*sb^2*vev^2), 0}},

C[ S[6] , S[1] , S[1] , -S[4] ] == {{((-I)*(cba^2*m122*sb^6 + cb*(-(cba^2*MHH^2*sb^5) + cba^4*(MHH^2 - MHL^2)*sb^7) + cb^7*cba^2*(MHH^2 - MHL^2)*sb*sba^2 + cb^4*cba*sb^2*(-(cba*m122) + 4*cba^2*(-MHH^2 + MHL^2)*sb^2*sba + 2*(MHL^2 - 2*MHp^2*sb^2)*sba) + cb^3*(MHH^2 - MHL^2)*sb^3*(cba^4*sb^2 - sba^2 + cba^2*sb^2*sba^2 + sb^2*sba^4) - cb^6*cba*(cba*m122 + cba^2*(MHH^2 - MHL^2)*sb^2*sba + sb^2*sba*(2*MHp^2 + (-MHH^2 + MHL^2)*sba^2)) + cb^2*cba*sb^4*(cba*m122 + 3*cba^2*(-MHH^2 + MHL^2)*sb^2*sba + sb^2*sba*(-2*MHp^2 + MHL^2*sba^2) + MHH^2*(2*sba - sb^2*sba^3)) + cb^5*((MHH^2 - MHL^2)*sb^3*sba^4 + cba^2*(2*MHH^2*sb^3*sba^2 + MHL^2*(sb - 2*sb^3*sba^2)))))/(cb^2*sb^2*vev^2), 0}},

C[ S[5] , S[3] , S[4] , -S[4] ] == {{((-I)*(cb^3*cba^2*(MHH^2 - MHL^2)*sb^5 + m122*sb^6 + cb*(-(cba^2*MHL^2*sb^7) + MHH^2*sb^5*(-1 + cba^2*sb^2)) + cb^7*(MHH^2 - MHL^2)*sb*sba^2 - cb^6*(m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) - cb^4*sb^2*(m122 + 2*cba*(MHH^2 - MHL^2)*sb^2*sba) + cb^2*sb^4*(m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^5*(MHH^2*sb^3*sba^2 + MHL^2*(sb - sb^3*sba^2))))/(cb^2*sb^2*vev^2), 0}},

C[ S[2] , S[1] , S[4] , -S[4] ] == {{(I*(-(cba*m122*sb^8*sba) + cb^9*cba*(MHH^2 - MHL^2)*sb*sba^3 + cb*sb^7*(-(cba^2*m122) + cba*MHH^2*sba + cba^3*(-MHH^2 + MHL^2)*sb^2*sba + m122*sba^2) + cb^4*cba*sb^4*(cba^3*(-MHH^2 + MHL^2)*sb^2 + 6*m122*sba + 2*cba*(MHH^2 - MHL^2)*sb^2*sba^2) - cb^8*sba*(cba*m122 + 2*cba^2*(MHH^2 - MHL^2)*sb^2*sba + (-MHH^2 + MHL^2)*sb^2*sba^3) - cb^5*sb^3*(-(cba^2*m122) + 3*cba^3*(-MHH^2 + MHL^2)*sb^2*sba + m122*sba^2 + cba*sba*(sb^2*(4*MHp^2 + 3*MHH^2*sba^2) + MHL^2*(1 - 3*sb^2*sba^2))) + cb^3*sb^5*(-(cba^2*m122) + cba^3*(MHH^2 - MHL^2)*sb^2*sba + m122*sba^2 - cba*sba*(sb^2*(2*MHp^2 - MHL^2*sba^2) + MHH^2*(1 + sb^2*sba^2))) + cb^7*sb*(cba^2*m122 + cba^3*(MHH^2 - MHL^2)*sb^2*sba - m122*sba^2 + cba*sba*(-(sb^2*(2*MHp^2 + MHH^2*sba^2)) + MHL^2*(1 + sb^2*sba^2))) + cb^6*sb^2*(2*cba*m122*sba + MHH^2*sb^2*sba^4 + MHL^2*(sba^2 - sb^2*sba^4) + cba^2*(-2*MHH^2*sb^2*sba^2 + MHL^2*(-1 + 2*sb^2*sba^2))) + cb^2*sb^6*(cba^4*(-MHH^2 + MHL^2)*sb^2 + 2*cba*m122*sba - MHH^2*sba^2 + cba^2*(-2*MHL^2*sb^2*sba^2 + MHH^2*(1 + 2*sb^2*sba^2)))))/(cb^3*sb^3*vev^2), 0}},

C[ -S[6] , S[4] , S[4] , -S[4] ] == {{((-2*I)*(cb^3*cba^2*(MHH^2 - MHL^2)*sb^5 + m122*sb^6 + cb*(-(cba^2*MHL^2*sb^7) + MHH^2*sb^5*(-1 + cba^2*sb^2)) + cb^7*(MHH^2 - MHL^2)*sb*sba^2 - cb^6*(m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) - cb^4*sb^2*(m122 + 2*cba*(MHH^2 - MHL^2)*sb^2*sba) + cb^2*sb^4*(m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^5*(MHH^2*sb^3*sba^2 + MHL^2*(sb - sb^3*sba^2))))/(cb^2*sb^2*vev^2), 0}},

C[ S[6] , S[4] , -S[4] , -S[4] ] == {{((-2*I)*(cb^3*cba^2*(MHH^2 - MHL^2)*sb^5 + m122*sb^6 + cb*(-(cba^2*MHL^2*sb^7) + MHH^2*sb^5*(-1 + cba^2*sb^2)) + cb^7*(MHH^2 - MHL^2)*sb*sba^2 - cb^6*(m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) - cb^4*sb^2*(m122 + 2*cba*(MHH^2 - MHL^2)*sb^2*sba) + cb^2*sb^4*(m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^5*(MHH^2*sb^3*sba^2 + MHL^2*(sb - sb^3*sba^2))))/(cb^2*sb^2*vev^2), 0}},

C[ S[3] , S[3] , S[2] , S[2] ] == {{((-I)*(-(m122*sb^8*sba^2) + cb^9*(MHH^2 - MHL^2)*sb*sba^4 + cb*sb^7*sba*(-2*cba*m122 + MHH^2*sba + cba^2*(-MHH^2 + MHL^2)*sb^2*sba) - cb^8*sba*(cba^3*(MHH^2 - MHL^2)*sb^2 + m122*sba + 4*cba*(MHH^2 - MHL^2)*sb^2*sba^2) + cb^4*sb^4*(-4*cba^2*m122 + cba^3*(-MHH^2 + MHL^2)*sb^2*sba + 2*m122*sba^2 + 2*cba*(MHH^2 - MHL^2)*sb^2*sba^3) + cb^7*sb*(cba^4*(MHH^2 - MHL^2)*sb^2 + 2*cba*m122*sba + MHL^2*sba^2 + cba^2*sb^2*(2*MHA^2 + 3*(MHH^2 - MHL^2)*sba^2)) + cb^2*cba*sb^6*(-2*cba*m122 + cba^2*(-MHH^2 + MHL^2)*sb^2*sba - 2*MHL^2*sb^2*sba^3 + 2*MHH^2*(sba + sb^2*sba^3)) + cb^6*cba*sb^2*(-2*cba*m122 + cba^2*(-MHH^2 + MHL^2)*sb^2*sba - 4*MHH^2*sb^2*sba^3 + MHL^2*(-2*sba + 4*sb^2*sba^3)) + cb^5*sb^3*(cba^4*(MHH^2 - MHL^2)*sb^2 + 2*cba*m122*sba + 2*(-MHH^2 + MHL^2)*sb^2*sba^4 + cba^2*(sb^2*(4*MHA^2 + 5*MHH^2*sba^2) + MHL^2*(1 - 5*sb^2*sba^2))) + cb^3*sb^5*(-2*cba*m122*sba + (-MHH^2 + MHL^2)*sb^2*sba^4 + cba^2*(sb^2*(2*MHA^2 - MHL^2*sba^2) + MHH^2*(1 + sb^2*sba^2)))))/(cb^3*sb^3*vev^2), 0}},

C[ S[5] , S[3] , S[2] , S[1] ] == {{(I*(cba*m122*sb^6*sba + cb*cba*sb^5*(-(cba^2*MHL^2*sb^2) + MHH^2*(-1 + cba^2*sb^2))*sba + cb^5*cba*sb*(-(cba^2*MHH^2*sb^2) + MHL^2*(1 + cba^2*sb^2))*sba + cb^7*cba*(MHH^2 - MHL^2)*sb*sba^3 - cb^3*cba*(MHH^2 - MHL^2)*sb^3*sba*(-1 + sb^2*sba^2) + cb^6*(-(cba*m122*sba) + sb^2*sba^2*(-MHA^2 + (MHH^2 - MHL^2)*sba^2) + cba^2*sb^2*(MHA^2 + (-MHH^2 + MHL^2)*sba^2)) - cb^4*sb^2*(cba^4*(-MHH^2 + MHL^2)*sb^2 + cba*m122*sba + cba^2*(-2*sb^2*(MHA^2 - MHH^2*sba^2) + MHL^2*(1 - 2*sb^2*sba^2)) + sba^2*(sb^2*(2*MHA^2 - MHH^2*sba^2) + MHL^2*(-1 + sb^2*sba^2))) + cb^2*sb^4*(cba^4*(MHH^2 - MHL^2)*sb^2 + cba*m122*sba + (MHH^2 - MHA^2*sb^2)*sba^2 + cba^2*(sb^2*(MHA^2 + MHL^2*sba^2) - MHH^2*(1 + sb^2*sba^2)))))/(cb^2*sb^2*vev^2), 0}},

C[ S[5] , S[5] , S[1] , S[1] ] == {{(I*(cb^6*cba^3*(MHH^2 - MHL^2)*sba + cba^2*sb^4*(2*m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^4*cba*(2*cba*m122 + cba^2*(-MHH^2 + MHL^2)*sb^2*sba + 2*(-MHH^2 + MHL^2)*sb^2*sba^3) + cb^5*sb*(cba^4*(-MHH^2 + MHL^2) + (MHH^2 - MHL^2)*sba^4 - 2*cba^2*(MHA^2 + (-MHH^2 + MHL^2)*sba^2)) + cb^2*cba*sb^2*(4*cba*m122 + 3*cba^2*(-MHH^2 + MHL^2)*sb^2*sba - 2*(MHH^2 - MHL^2)*sba*(-1 + sb^2*sba^2)) + cb*sb^3*(-(MHL^2*sba^2) + cba^2*(-2*sb^2*(MHA^2 + MHL^2*sba^2) + MHH^2*(-1 + 2*sb^2*sba^2))) + cb^3*sb*(cba^4*(-MHH^2 + MHL^2)*sb^2 - MHL^2*sb^2*sba^4 + MHH^2*sba^2*(-1 + sb^2*sba^2) - cba^2*(4*sb^2*(MHA^2 - MHH^2*sba^2) + MHL^2*(1 + 4*sb^2*sba^2)))))/(cb*sb*vev^2), 0}},

C[ -S[6] , S[3] , S[2] , S[4] ] == {{-((cba*(MHA - MHp)*(MHA + MHp)*(cb^2 + sb^2)^2)/vev^2), 0}},

C[ S[5] , -S[6] , S[1] , S[4] ] == {{(cba*(MHA - MHp)*(MHA + MHp)*(cb^2 + sb^2)^2)/vev^2, 0}},

C[ -S[6] , -S[6] , S[4] , S[4] ] == {{((2*I)*((MHA^2 - cba^2*MHL^2)*sb^4 + MHH^2*sb^2*(-1 + cba^2*sb^2) + cb^4*(MHA^2 + (-MHH^2 + MHL^2)*sba^2) - cb^2*(MHL^2*(1 + cba^2*sb^2 - sb^2*sba^2) + sb^2*(-2*MHA^2 + MHH^2*(-cba^2 + sba^2)))))/vev^2, 0}},

C[ S[6] , S[3] , S[2] , -S[4] ] == {{(cba*(MHA - MHp)*(MHA + MHp)*(cb^2 + sb^2)^2)/vev^2, 0}},

C[ S[5] , S[6] , S[1] , -S[4] ] == {{-((cba*(MHA - MHp)*(MHA + MHp)*(cb^2 + sb^2)^2)/vev^2), 0}},

C[ S[6] , -S[6] , S[4] , -S[4] ] == {{(I*(2*m122*sb^4 - 2*cb^3*sb*(MHL^2 + MHA^2*sb^2) + cb^6*cba*(MHH^2 - MHL^2)*sba + cba*(-MHH^2 + MHL^2)*sb^6*sba + cb^4*(2*m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) + cb^2*(4*m122*sb^2 + cba*(-MHH^2 + MHL^2)*sb^4*sba) - cb^5*sb*(MHA^2 + (MHH^2 - MHL^2)*(cba^2 + sba^2)) + cb*(MHH^2*sb^3*(-2 + cba^2*sb^2 + sb^2*sba^2) - sb^5*(MHA^2 + MHL^2*(cba^2 + sba^2)))))/(cb*sb*vev^2), 0}},

C[ S[6] , S[6] , -S[4] , -S[4] ] == {{((2*I)*((MHA^2 - cba^2*MHL^2)*sb^4 + MHH^2*sb^2*(-1 + cba^2*sb^2) + cb^4*(MHA^2 + (-MHH^2 + MHL^2)*sba^2) - cb^2*(MHL^2*(1 + cba^2*sb^2 - sb^2*sba^2) + sb^2*(-2*MHA^2 + MHH^2*(-cba^2 + sba^2)))))/vev^2, 0}},

C[ S[5] , S[5] , S[5] , S[5] ] == {{((-3*I)*(cba^2*MHH^2*sb^4 + MHL^2*(sb^2 - cba^2*sb^4) + cb^4*(-MHH^2 + MHL^2)*sba^2 + cb^2*(MHL^2*sb^2*(-cba^2 + sba^2) + MHH^2*(1 + cba^2*sb^2 - sb^2*sba^2))))/vev^2, 0}},

C[ S[5] , S[5] , S[6] , -S[6] ] == {{((-I)*(cba^2*MHH^2*sb^4 + MHL^2*(sb^2 - cba^2*sb^4) + cb^4*(-MHH^2 + MHL^2)*sba^2 + cb^2*(MHL^2*sb^2*(-cba^2 + sba^2) + MHH^2*(1 + cba^2*sb^2 - sb^2*sba^2))))/vev^2, 0}},

C[ S[6] , S[6] , -S[6] , -S[6] ] == {{((-2*I)*(cba^2*MHH^2*sb^4 + MHL^2*(sb^2 - cba^2*sb^4) + cb^4*(-MHH^2 + MHL^2)*sba^2 + cb^2*(MHL^2*sb^2*(-cba^2 + sba^2) + MHH^2*(1 + cba^2*sb^2 - sb^2*sba^2))))/vev^2, 0}},

C[ S[5] , S[5] , S[3] , S[3] ] == {{(I*(2*m122*sb^4 + cb^6*cba*(MHH^2 - MHL^2)*sba + cba*(-MHH^2 + MHL^2)*sb^6*sba + cb^4*(2*m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) + cb^2*(4*m122*sb^2 + cba*(-MHH^2 + MHL^2)*sb^4*sba) - cb^5*(MHH^2 - MHL^2)*sb*(cba^2 + 2*sba^2) + cb*(-(MHL^2*sb^5*(2*cba^2 + sba^2)) + MHH^2*sb^3*(-3 + 2*cba^2*sb^2 + sb^2*sba^2)) + cb^3*(MHH^2*sb^3*(cba^2 - sba^2) + MHL^2*(-3*sb + sb^3*(-cba^2 + sba^2)))))/(cb*sb*vev^2), 0}},

C[ S[6] , -S[6] , S[3] , S[3] ] == {{(I*(cb^5*(cba^2*(-MHH^2 + MHL^2) - 2*MHp^2)*sb + 2*m122*sb^4 + cb^6*cba*(MHH^2 - MHL^2)*sba + cba*(-MHH^2 + MHL^2)*sb^6*sba + cb^4*(2*m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) + cb^2*(4*m122*sb^2 + cba*(-MHH^2 + MHL^2)*sb^4*sba) + cb^3*(sb^3*(-(cba^2*MHH^2) - 4*MHp^2 + MHH^2*sba^2) + MHL^2*sb*(-1 + cba^2*sb^2 - sb^2*sba^2)) + cb*(-(sb^5*(2*MHp^2 + MHL^2*sba^2)) + MHH^2*sb^3*(-1 + sb^2*sba^2))))/(cb*sb*vev^2), 0}},

C[ S[3] , S[3] , S[3] , S[3] ] == {{((-3*I)*(-(m122*sb^8) + cb^7*(cba^2*MHH^2*sb^3 + MHL^2*(sb - cba^2*sb^3)) + cb*(cba^2*MHL^2*sb^9 + MHH^2*(sb^7 - cba^2*sb^9)) + 2*cb^6*cba*(-MHH^2 + MHL^2)*sb^4*sba + 2*cb^2*cba*(MHH^2 - MHL^2)*sb^8*sba + cb^9*(MHH^2 - MHL^2)*sb*sba^2 + cb^3*(-MHH^2 + MHL^2)*sb^7*sba^2 + 2*cb^4*sb^4*(m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) - cb^8*(m122 + 2*cba*(MHH^2 - MHL^2)*sb^2*sba) + 2*cb^5*(MHH^2 - MHL^2)*sb^5*(cba^2 - sba^2)))/(cb^3*sb^3*vev^2), 0}},

C[ S[5] , S[5] , S[2] , S[2] ] == {{(I*(-2*cb^5*(MHA^2 + cba^2*(MHH^2 - MHL^2))*sb*sba^2 + cb^6*cba*(MHH^2 - MHL^2)*sba^3 + sb^4*sba^2*(2*m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^4*sba*(2*cba^3*(MHH^2 - MHL^2)*sb^2 + 2*m122*sba + 3*cba*(MHH^2 - MHL^2)*sb^2*sba^2) + cb^2*sb^2*sba*(2*cba^3*(MHH^2 - MHL^2)*sb^2 + 4*m122*sba + cba*(MHH^2 - MHL^2)*(-2 + sb^2*sba^2)) + cb*sb^3*(cba^4*(-MHH^2 + MHL^2)*sb^2 + sba^2*(-(sb^2*(2*MHA^2 + MHL^2*sba^2)) + MHH^2*(-1 + sb^2*sba^2)) + cba^2*(-2*MHH^2*sb^2*sba^2 + MHL^2*(-1 + 2*sb^2*sba^2))) - cb^3*sb*(cba^4*(MHH^2 - MHL^2)*sb^2 + sba^2*(sb^2*(4*MHA^2 - MHH^2*sba^2) + MHL^2*(1 + sb^2*sba^2)) + cba^2*(-4*MHL^2*sb^2*sba^2 + MHH^2*(1 + 4*sb^2*sba^2)))))/(cb*sb*vev^2), 0}},

C[ S[6] , -S[6] , S[2] , S[2] ] == {{(I*(-2*cb^5*(cba^2*(MHH^2 - MHL^2) + MHp^2)*sb*sba^2 + cb^6*cba*(MHH^2 - MHL^2)*sba^3 + sb^4*sba^2*(2*m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^4*sba*(2*cba^3*(MHH^2 - MHL^2)*sb^2 + 2*m122*sba + 3*cba*(MHH^2 - MHL^2)*sb^2*sba^2) + cb^2*sb^2*sba*(2*cba^3*(MHH^2 - MHL^2)*sb^2 + 4*m122*sba + cba*(MHH^2 - MHL^2)*(-2 + sb^2*sba^2)) + cb*sb^3*(cba^4*(-MHH^2 + MHL^2)*sb^2 + sba^2*(-(sb^2*(2*MHp^2 + MHL^2*sba^2)) + MHH^2*(-1 + sb^2*sba^2)) + cba^2*(-2*MHH^2*sb^2*sba^2 + MHL^2*(-1 + 2*sb^2*sba^2))) - cb^3*sb*(cba^4*(MHH^2 - MHL^2)*sb^2 + sba^2*(sb^2*(4*MHp^2 - MHH^2*sba^2) + MHL^2*(1 + sb^2*sba^2)) + cba^2*(-4*MHL^2*sb^2*sba^2 + MHH^2*(1 + 4*sb^2*sba^2)))))/(cb*sb*vev^2), 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{((-3*I)*(-(m122*sb^8*sba^4) + cb^9*(MHH^2 - MHL^2)*sb*sba^6 + cb*sb^7*sba^3*(-4*cba*m122 + MHH^2*sba + cba^2*(-MHH^2 + MHL^2)*sb^2*sba) - cb^8*sba^3*(2*cba^3*(MHH^2 - MHL^2)*sb^2 + m122*sba + 6*cba*(MHH^2 - MHL^2)*sb^2*sba^2) + cb^7*sb*sba^2*(5*cba^4*(MHH^2 - MHL^2)*sb^2 + 4*cba*m122*sba + MHL^2*sba^2 + 9*cba^2*(MHH^2 - MHL^2)*sb^2*sba^2) - 2*cb^2*cba*sb^6*sba^2*(2*cba*m122 + cba^2*(MHH^2 - MHL^2)*sb^2*sba + MHL^2*sb^2*sba^3 - MHH^2*sba*(2 + sb^2*sba^2)) + 2*cb^4*sb^4*sba*(2*cba^5*(-MHH^2 + MHL^2)*sb^2 - 4*cba^2*m122*sba + m122*sba^3 + cba*(MHH^2 - MHL^2)*sb^2*sba^4 - cba^3*(MHH^2 - MHL^2)*(-2 + 3*sb^2*sba^2)) - 2*cb^6*cba*sb^2*sba*(2*cba^4*(MHH^2 - MHL^2)*sb^2 + 2*cba*m122*sba + 3*cba^2*(MHH^2 - MHL^2)*sb^2*sba^2 + 3*MHH^2*sb^2*sba^4 + MHL^2*(2*sba^2 - 3*sb^2*sba^4)) + cb^3*sb^5*(cba^4*MHL^2 + cba^6*(MHH^2 - MHL^2)*sb^2 - 4*cba*m122*sba^3 + (-MHH^2 + MHL^2)*sb^2*sba^6 + 2*cba^2*(-(MHL^2*sb^2*sba^4) + MHH^2*sba^2*(3 + sb^2*sba^2))) + cb^5*sb^3*(cba^6*(MHH^2 - MHL^2)*sb^2 + 4*cba*m122*sba^3 + 2*(-MHH^2 + MHL^2)*sb^2*sba^6 + cba^4*(-5*MHL^2*sb^2*sba^2 + MHH^2*(1 + 5*sb^2*sba^2)) + 6*cba^2*(2*MHH^2*sb^2*sba^4 + MHL^2*(sba^2 - 2*sb^2*sba^4)))))/(cb^3*sb^3*vev^2), 0}},

C[ S[6] , -S[6] , S[1] , S[1] ] == {{(I*(cb^6*cba^3*(MHH^2 - MHL^2)*sba + cba^2*sb^4*(2*m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^4*cba*(2*cba*m122 + cba^2*(-MHH^2 + MHL^2)*sb^2*sba + 2*(-MHH^2 + MHL^2)*sb^2*sba^3) + cb^5*sb*(cba^4*(-MHH^2 + MHL^2) + (MHH^2 - MHL^2)*sba^4 - 2*cba^2*(MHp^2 + (-MHH^2 + MHL^2)*sba^2)) + cb^2*cba*sb^2*(4*cba*m122 + 3*cba^2*(-MHH^2 + MHL^2)*sb^2*sba - 2*(MHH^2 - MHL^2)*sba*(-1 + sb^2*sba^2)) + cb*sb^3*(-(MHL^2*sba^2) + cba^2*(-2*sb^2*(MHp^2 + MHL^2*sba^2) + MHH^2*(-1 + 2*sb^2*sba^2))) + cb^3*sb*(cba^4*(-MHH^2 + MHL^2)*sb^2 - MHL^2*sb^2*sba^4 + MHH^2*sba^2*(-1 + sb^2*sba^2) - cba^2*(4*sb^2*(MHp^2 - MHH^2*sba^2) + MHL^2*(1 + 4*sb^2*sba^2)))))/(cb*sb*vev^2), 0}},

C[ S[3] , S[3] , S[1] , S[1] ] == {{((-I)*(-(cba^2*m122*sb^8) + cb^9*cba^2*(MHH^2 - MHL^2)*sb*sba^2 + cb*cba*sb^7*(cba*MHH^2 + cba^3*(-MHH^2 + MHL^2)*sb^2 + 2*m122*sba) + cb^4*sb^4*(2*cba^2*m122 + 4*cba^3*(MHH^2 - MHL^2)*sb^2*sba - 4*m122*sba^2 + cba*(MHH^2 - MHL^2)*sb^2*sba^3) - cb^8*cba*(cba*m122 + 2*cba^2*(MHH^2 - MHL^2)*sb^2*sba + (-MHH^2 + MHL^2)*sb^2*sba^3) + cb^3*sb^5*sba*(2*cba*m122 + 3*cba^2*(-MHH^2 + MHL^2)*sb^2*sba + sb^2*sba*(2*MHA^2 + MHL^2*sba^2) + MHH^2*sba*(1 - sb^2*sba^2)) + cb^6*sb^2*sba*(2*cba^3*(-MHH^2 + MHL^2)*sb^2 - 2*m122*sba + cba*MHH^2*sb^2*sba^2 + cba*MHL^2*(2 - sb^2*sba^2)) + cb^2*sb^6*sba*(4*cba^3*(MHH^2 - MHL^2)*sb^2 - 2*m122*sba - cba*MHL^2*sb^2*sba^2 + cba*MHH^2*(-2 + sb^2*sba^2)) + cb^5*sb^3*(2*cba^4*(MHH^2 - MHL^2)*sb^2 - 2*cba*m122*sba + 5*cba^2*(-MHH^2 + MHL^2)*sb^2*sba^2 + sba^2*(sb^2*(4*MHA^2 - MHH^2*sba^2) + MHL^2*(1 + sb^2*sba^2))) + cb^7*(cba^4*(MHH^2 - MHL^2)*sb^3 - 2*cba*m122*sb*sba + 2*MHA^2*sb^3*sba^2 + cba^2*(-(MHH^2*sb^3*sba^2) + MHL^2*(sb + sb^3*sba^2)))))/(cb^3*sb^3*vev^2), 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{((-I)*(-3*cba^2*m122*sb^8*sba^2 + 3*cb^9*cba^2*(MHH^2 - MHL^2)*sb*sba^4 + 3*cb*cba*sb^7*sba*(-2*cba^2*m122 + cba*MHH^2*sba + cba^3*(-MHH^2 + MHL^2)*sb^2*sba + 2*m122*sba^2) + cb^8*cba*sba*(cba^4*(-MHH^2 + MHL^2)*sb^2 - 3*cba*m122*sba + 8*cba^2*(-MHH^2 + MHL^2)*sb^2*sba^2 + 5*(MHH^2 - MHL^2)*sb^2*sba^4) + cb^4*sb^4*(-4*cba^4*m122 + cba^5*(MHH^2 - MHL^2)*sb^2*sba + 22*cba^2*m122*sba^2 - 4*m122*sba^4 + 2*cba^3*(MHH^2 - MHL^2)*sba*(-3 + 4*sb^2*sba^2) - cba*(MHH^2 - MHL^2)*sba^3*(-6 + 5*sb^2*sba^2)) + cb^5*sb^3*(cba^6*(-MHH^2 + MHL^2)*sb^2 + 6*cba^3*m122*sba - 6*cba*m122*sba^3 + MHH^2*sb^2*sba^6 + MHL^2*(3*sba^4 - sb^2*sba^6) + cba^4*(14*MHH^2*sb^2*sba^2 + MHL^2*(3 - 14*sb^2*sba^2)) + cba^2*sba^2*(MHH^2*(3 - 14*sb^2*sba^2) + 2*MHL^2*(-6 + 7*sb^2*sba^2))) + cb^3*sb^5*(2*cba^6*(-MHH^2 + MHL^2)*sb^2 - 6*cba^3*m122*sba + 6*cba*m122*sba^3 + MHL^2*sb^2*sba^6 + MHH^2*(3*sba^4 - sb^2*sba^6) + cba^2*sba^2*(MHL^2*(3 + sb^2*sba^2) - MHH^2*(12 + sb^2*sba^2)) + cba^4*(-10*MHL^2*sb^2*sba^2 + MHH^2*(3 + 10*sb^2*sba^2))) + cb^7*sb*(cba^6*(MHH^2 - MHL^2)*sb^2 + 6*cba^3*m122*sba + cba^4*(MHH^2 - MHL^2)*sb^2*sba^2 - 6*cba*m122*sba^3 + 2*(MHH^2 - MHL^2)*sb^2*sba^6 + cba^2*(-10*MHH^2*sb^2*sba^4 + MHL^2*sba^2*(3 + 10*sb^2*sba^2))) + cb^6*sb^2*(-2*cba^4*m122 + 5*cba^5*(MHH^2 - MHL^2)*sb^2*sba + 8*cba^2*m122*sba^2 - 2*m122*sba^4 + cba*(-(MHH^2*sb^2*sba^5) + MHL^2*sba^3*(6 + sb^2*sba^2)) + cba^3*(-8*MHH^2*sb^2*sba^3 + MHL^2*(-6*sba + 8*sb^2*sba^3))) + cb^2*sb^6*(-2*cba^4*m122 + 5*cba^5*(-MHH^2 + MHL^2)*sb^2*sba + 8*cba^2*m122*sba^2 - 2*m122*sba^4 + cba*(-(MHL^2*sb^2*sba^5) + MHH^2*sba^3*(-6 + sb^2*sba^2)) + cba^3*(-8*MHL^2*sb^2*sba^3 + MHH^2*(6*sba + 8*sb^2*sba^3)))))/(cb^3*sb^3*vev^2), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{((-3*I)*(-(cba^4*m122*sb^8) + cb^9*cba^4*(MHH^2 - MHL^2)*sb*sba^2 + cb*cba^3*sb^7*(cba*MHH^2 + cba^3*(-MHH^2 + MHL^2)*sb^2 + 4*m122*sba) - cb^8*cba^3*(cba*m122 + 2*cba^2*(MHH^2 - MHL^2)*sb^2*sba + 2*(-MHH^2 + MHL^2)*sb^2*sba^3) + 2*cb^2*cba^2*sb^6*sba*(3*cba^3*(MHH^2 - MHL^2)*sb^2 - 2*m122*sba - cba*MHL^2*sb^2*sba^2 + cba*MHH^2*(-2 + sb^2*sba^2)) + 2*cb^4*cba*sb^4*(cba^3*m122 + 3*cba^4*(MHH^2 - MHL^2)*sb^2*sba - 4*cba*m122*sba^2 + 3*cba^2*(MHH^2 - MHL^2)*sb^2*sba^3 + 2*(MHH^2 - MHL^2)*sba^3*(-1 + sb^2*sba^2)) + 2*cb^6*cba*sb^2*sba*(cba^4*(-MHH^2 + MHL^2)*sb^2 - 2*cba*m122*sba + 2*(MHH^2 - MHL^2)*sb^2*sba^4 + cba^2*(3*MHH^2*sb^2*sba^2 + MHL^2*(2 - 3*sb^2*sba^2))) + cb^5*sb^3*(2*cba^6*(MHH^2 - MHL^2)*sb^2 - 4*cba^3*m122*sba - 12*cba^4*(MHH^2 - MHL^2)*sb^2*sba^2 + MHL^2*sb^2*sba^6 + MHH^2*(sba^4 - sb^2*sba^6) + cba^2*(-5*MHH^2*sb^2*sba^4 + MHL^2*sba^2*(6 + 5*sb^2*sba^2))) + cb^7*(cba^6*(MHH^2 - MHL^2)*sb^3 - 4*cba^3*m122*sb*sba + (-MHH^2 + MHL^2)*sb^3*sba^6 + cba^4*(-2*MHH^2*sb^3*sba^2 + MHL^2*(sb + 2*sb^3*sba^2))) + cb^3*sb^5*sba*(4*cba^3*m122 + 9*cba^4*(-MHH^2 + MHL^2)*sb^2*sba + MHL^2*sba^3 + cba^2*(5*MHL^2*sb^2*sba^3 + MHH^2*(6*sba - 5*sb^2*sba^3)))))/(cb^3*sb^3*vev^2), 0}},

C[ S[5] , S[5] , S[4] , -S[4] ] == {{(I*(cb^5*(cba^2*(-MHH^2 + MHL^2) - 2*MHp^2)*sb + 2*m122*sb^4 + cb^6*cba*(MHH^2 - MHL^2)*sba + cba*(-MHH^2 + MHL^2)*sb^6*sba + cb^4*(2*m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) + cb^2*(4*m122*sb^2 + cba*(-MHH^2 + MHL^2)*sb^4*sba) + cb^3*(sb^3*(-(cba^2*MHH^2) - 4*MHp^2 + MHH^2*sba^2) + MHL^2*sb*(-1 + cba^2*sb^2 - sb^2*sba^2)) + cb*(-(sb^5*(2*MHp^2 + MHL^2*sba^2)) + MHH^2*sb^3*(-1 + sb^2*sba^2))))/(cb*sb*vev^2), 0}},

C[ S[3] , S[3] , S[4] , -S[4] ] == {{((-I)*(-(m122*sb^8) + cb^7*(cba^2*MHH^2*sb^3 + MHL^2*(sb - cba^2*sb^3)) + cb*(cba^2*MHL^2*sb^9 + MHH^2*(sb^7 - cba^2*sb^9)) + 2*cb^6*cba*(-MHH^2 + MHL^2)*sb^4*sba + 2*cb^2*cba*(MHH^2 - MHL^2)*sb^8*sba + cb^9*(MHH^2 - MHL^2)*sb*sba^2 + cb^3*(-MHH^2 + MHL^2)*sb^7*sba^2 + 2*cb^4*sb^4*(m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) - cb^8*(m122 + 2*cba*(MHH^2 - MHL^2)*sb^2*sba) + 2*cb^5*(MHH^2 - MHL^2)*sb^5*(cba^2 - sba^2)))/(cb^3*sb^3*vev^2), 0}},

C[ S[2] , S[2] , S[4] , -S[4] ] == {{((-I)*(-(m122*sb^8*sba^2) + cb^9*(MHH^2 - MHL^2)*sb*sba^4 + cb*sb^7*sba*(-2*cba*m122 + MHH^2*sba + cba^2*(-MHH^2 + MHL^2)*sb^2*sba) - cb^8*sba*(cba^3*(MHH^2 - MHL^2)*sb^2 + m122*sba + 4*cba*(MHH^2 - MHL^2)*sb^2*sba^2) + cb^4*sb^4*(-4*cba^2*m122 + cba^3*(-MHH^2 + MHL^2)*sb^2*sba + 2*m122*sba^2 + 2*cba*(MHH^2 - MHL^2)*sb^2*sba^3) + cb^7*sb*(cba^4*(MHH^2 - MHL^2)*sb^2 + 2*cba*m122*sba + MHL^2*sba^2 + cba^2*sb^2*(2*MHp^2 + 3*(MHH^2 - MHL^2)*sba^2)) + cb^2*cba*sb^6*(-2*cba*m122 + cba^2*(-MHH^2 + MHL^2)*sb^2*sba - 2*MHL^2*sb^2*sba^3 + 2*MHH^2*(sba + sb^2*sba^3)) + cb^6*cba*sb^2*(-2*cba*m122 + cba^2*(-MHH^2 + MHL^2)*sb^2*sba - 4*MHH^2*sb^2*sba^3 + MHL^2*(-2*sba + 4*sb^2*sba^3)) + cb^5*sb^3*(cba^4*(MHH^2 - MHL^2)*sb^2 + 2*cba*m122*sba + 2*(-MHH^2 + MHL^2)*sb^2*sba^4 + cba^2*(sb^2*(4*MHp^2 + 5*MHH^2*sba^2) + MHL^2*(1 - 5*sb^2*sba^2))) + cb^3*sb^5*(-2*cba*m122*sba + (-MHH^2 + MHL^2)*sb^2*sba^4 + cba^2*(sb^2*(2*MHp^2 - MHL^2*sba^2) + MHH^2*(1 + sb^2*sba^2)))))/(cb^3*sb^3*vev^2), 0}},

C[ S[1] , S[1] , S[4] , -S[4] ] == {{((-I)*(-(cba^2*m122*sb^8) + cb^9*cba^2*(MHH^2 - MHL^2)*sb*sba^2 + cb*cba*sb^7*(cba*MHH^2 + cba^3*(-MHH^2 + MHL^2)*sb^2 + 2*m122*sba) + cb^4*sb^4*(2*cba^2*m122 + 4*cba^3*(MHH^2 - MHL^2)*sb^2*sba - 4*m122*sba^2 + cba*(MHH^2 - MHL^2)*sb^2*sba^3) - cb^8*cba*(cba*m122 + 2*cba^2*(MHH^2 - MHL^2)*sb^2*sba + (-MHH^2 + MHL^2)*sb^2*sba^3) + cb^3*sb^5*sba*(2*cba*m122 + 3*cba^2*(-MHH^2 + MHL^2)*sb^2*sba + sb^2*sba*(2*MHp^2 + MHL^2*sba^2) + MHH^2*sba*(1 - sb^2*sba^2)) + cb^6*sb^2*sba*(2*cba^3*(-MHH^2 + MHL^2)*sb^2 - 2*m122*sba + cba*MHH^2*sb^2*sba^2 + cba*MHL^2*(2 - sb^2*sba^2)) + cb^2*sb^6*sba*(4*cba^3*(MHH^2 - MHL^2)*sb^2 - 2*m122*sba - cba*MHL^2*sb^2*sba^2 + cba*MHH^2*(-2 + sb^2*sba^2)) + cb^5*sb^3*(2*cba^4*(MHH^2 - MHL^2)*sb^2 - 2*cba*m122*sba + 5*cba^2*(-MHH^2 + MHL^2)*sb^2*sba^2 + sba^2*(sb^2*(4*MHp^2 - MHH^2*sba^2) + MHL^2*(1 + sb^2*sba^2))) + cb^7*(cba^4*(MHH^2 - MHL^2)*sb^3 - 2*cba*m122*sb*sba + 2*MHp^2*sb^3*sba^2 + cba^2*(-(MHH^2*sb^3*sba^2) + MHL^2*(sb + sb^3*sba^2)))))/(cb^3*sb^3*vev^2), 0}},

C[ S[4] , S[4] , -S[4] , -S[4] ] == {{((-2*I)*(-(m122*sb^8) + cb^7*(cba^2*MHH^2*sb^3 + MHL^2*(sb - cba^2*sb^3)) + cb*(cba^2*MHL^2*sb^9 + MHH^2*(sb^7 - cba^2*sb^9)) + 2*cb^6*cba*(-MHH^2 + MHL^2)*sb^4*sba + 2*cb^2*cba*(MHH^2 - MHL^2)*sb^8*sba + cb^9*(MHH^2 - MHL^2)*sb*sba^2 + cb^3*(-MHH^2 + MHL^2)*sb^7*sba^2 + 2*cb^4*sb^4*(m122 + cba*(MHH^2 - MHL^2)*sb^2*sba) - cb^8*(m122 + 2*cba*(MHH^2 - MHL^2)*sb^2*sba) + 2*cb^5*(MHH^2 - MHL^2)*sb^5*(cba^2 - sba^2)))/(cb^3*sb^3*vev^2), 0}},

C[ S[5] , -S[6] , S[3] , S[4] ] == {{((-I)*((cba^2*MHL^2 - MHp^2)*sb^4 + MHH^2*(sb^2 - cba^2*sb^4) - cb^4*(MHp^2 + (-MHH^2 + MHL^2)*sba^2) + cb^2*(sb^2*(-(cba^2*MHH^2) - 2*MHp^2 + MHH^2*sba^2) + MHL^2*(1 + cba^2*sb^2 - sb^2*sba^2))))/vev^2, 0}},

C[ -S[6] , S[2] , S[1] , S[4] ] == {{(I*(cba*m122*sb^6*sba + cb*cba*sb^5*(-(cba^2*MHL^2*sb^2) + MHH^2*(-1 + cba^2*sb^2))*sba + cb^5*cba*sb*(-(cba^2*MHH^2*sb^2) + MHL^2*(1 + cba^2*sb^2))*sba + cb^7*cba*(MHH^2 - MHL^2)*sb*sba^3 - cb^3*cba*(MHH^2 - MHL^2)*sb^3*sba*(-1 + sb^2*sba^2) + cb^6*(-(cba*m122*sba) + sb^2*sba^2*(-MHp^2 + (MHH^2 - MHL^2)*sba^2) + cba^2*sb^2*(MHp^2 + (-MHH^2 + MHL^2)*sba^2)) - cb^4*sb^2*(cba^4*(-MHH^2 + MHL^2)*sb^2 + cba*m122*sba + cba^2*(-2*sb^2*(MHp^2 - MHH^2*sba^2) + MHL^2*(1 - 2*sb^2*sba^2)) + sba^2*(sb^2*(2*MHp^2 - MHH^2*sba^2) + MHL^2*(-1 + sb^2*sba^2))) + cb^2*sb^4*(cba^4*(MHH^2 - MHL^2)*sb^2 + cba*m122*sba + (MHH^2 - MHp^2*sb^2)*sba^2 + cba^2*(sb^2*(MHp^2 + MHL^2*sba^2) - MHH^2*(1 + sb^2*sba^2)))))/(cb^2*sb^2*vev^2), 0}},

C[ S[5] , S[6] , S[3] , -S[4] ] == {{((-I)*((cba^2*MHL^2 - MHp^2)*sb^4 + MHH^2*(sb^2 - cba^2*sb^4) - cb^4*(MHp^2 + (-MHH^2 + MHL^2)*sba^2) + cb^2*(sb^2*(-(cba^2*MHH^2) - 2*MHp^2 + MHH^2*sba^2) + MHL^2*(1 + cba^2*sb^2 - sb^2*sba^2))))/vev^2, 0}},

C[ S[6] , S[2] , S[1] , -S[4] ] == {{(I*(cba*m122*sb^6*sba + cb*cba*sb^5*(-(cba^2*MHL^2*sb^2) + MHH^2*(-1 + cba^2*sb^2))*sba + cb^5*cba*sb*(-(cba^2*MHH^2*sb^2) + MHL^2*(1 + cba^2*sb^2))*sba + cb^7*cba*(MHH^2 - MHL^2)*sb*sba^3 - cb^3*cba*(MHH^2 - MHL^2)*sb^3*sba*(-1 + sb^2*sba^2) + cb^6*(-(cba*m122*sba) + sb^2*sba^2*(-MHp^2 + (MHH^2 - MHL^2)*sba^2) + cba^2*sb^2*(MHp^2 + (-MHH^2 + MHL^2)*sba^2)) - cb^4*sb^2*(cba^4*(-MHH^2 + MHL^2)*sb^2 + cba*m122*sba + cba^2*(-2*sb^2*(MHp^2 - MHH^2*sba^2) + MHL^2*(1 - 2*sb^2*sba^2)) + sba^2*(sb^2*(2*MHp^2 - MHH^2*sba^2) + MHL^2*(-1 + sb^2*sba^2))) + cb^2*sb^4*(cba^4*(MHH^2 - MHL^2)*sb^2 + cba*m122*sba + (MHH^2 - MHp^2*sb^2)*sba^2 + cba^2*(sb^2*(MHp^2 + MHL^2*sba^2) - MHH^2*(1 + sb^2*sba^2)))))/(cb^2*sb^2*vev^2), 0}},

C[ S[5] , S[5] , S[5] , S[3] ] == {{((3*I)*(MHH - MHL)*(MHH + MHL)*(cb^4*cba*sba + 2*cb^2*cba*sb^2*sba + cba*sb^4*sba - cb^3*sb*(cba^2 + sba^2) + cb*(sb - sb^3*(cba^2 + sba^2))))/vev^2, 0}},

C[ S[5] , S[6] , -S[6] , S[3] ] == {{(I*(MHH - MHL)*(MHH + MHL)*(cb^4*cba*sba + 2*cb^2*cba*sb^2*sba + cba*sb^4*sba - cb^3*sb*(cba^2 + sba^2) + cb*(sb - sb^3*(cba^2 + sba^2))))/vev^2, 0}},

C[ S[5] , S[3] , S[2] , S[2] ] == {{((-I)*(m122*sb^6*sba^2 + cb*sb^5*(-(cba^2*MHL^2*sb^2) + MHH^2*(-1 + cba^2*sb^2))*sba^2 + cb^7*(MHH^2 - MHL^2)*sb*sba^4 + cb^3*cba^2*(MHH^2 - MHL^2)*sb^3*(-1 + cba^2*sb^2 + 2*sb^2*sba^2) + cb^6*sba*(cba^3*(-MHH^2 + MHL^2)*sb^2 - m122*sba + cba*sb^2*(2*MHA^2 + 3*(-MHH^2 + MHL^2)*sba^2)) + cb^2*sb^4*sba*(cba^3*(MHH^2 - MHL^2)*sb^2 + m122*sba + cba*sb^2*(2*MHA^2 + MHL^2*sba^2) - cba*MHH^2*(2 + sb^2*sba^2)) + cb^4*sb^2*sba*(-(m122*sba) + 4*cba*sb^2*(MHA^2 - MHH^2*sba^2) + cba*MHL^2*(-2 + 4*sb^2*sba^2)) + cb^5*(cba^4*(MHH^2 - MHL^2)*sb^3 + cba^2*(MHH^2 - MHL^2)*sb^3*sba^2 + MHH^2*sb^3*sba^4 + MHL^2*(sb*sba^2 - sb^3*sba^4))))/(cb^2*sb^2*vev^2), 0}},

C[ S[5] , S[5] , S[2] , S[1] ] == {{((-I)*(-2*cb^5*cba*(MHA^2 + cba^2*(MHH^2 - MHL^2))*sb*sba + cb^6*cba^2*(MHH^2 - MHL^2)*sba^2 + cba*sb^4*sba*(2*m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^4*(cba^4*(MHH^2 - MHL^2)*sb^2 + 2*cba*m122*sba + cba^2*(MHH^2 - MHL^2)*sb^2*sba^2 + (-MHH^2 + MHL^2)*sb^2*sba^4) + cb^2*sb^2*(cba^4*(MHH^2 - MHL^2)*sb^2 + 4*cba*m122*sba - (MHH^2 - MHL^2)*sba^2*(-1 + sb^2*sba^2) - cba^2*(MHH^2 - MHL^2)*(1 + sb^2*sba^2)) + cb*cba*sb^3*sba*(-2*MHA^2*sb^2 + MHL^2*(1 - 2*sb^2*sba^2) + MHH^2*(-1 + 2*sb^2*sba^2)) + cb^3*cba*sb*sba*(-4*MHA^2*sb^2 + MHL^2*(-1 + 2*cba^2*sb^2 - 2*sb^2*sba^2) + MHH^2*(1 - 2*cba^2*sb^2 + 2*sb^2*sba^2))))/(cb*sb*vev^2), 0}},

C[ S[6] , -S[6] , S[2] , S[1] ] == {{((-I)*(-2*cb^5*cba*(cba^2*(MHH^2 - MHL^2) + MHp^2)*sb*sba + cb^6*cba^2*(MHH^2 - MHL^2)*sba^2 + cba*sb^4*sba*(2*m122 + cba*(-MHH^2 + MHL^2)*sb^2*sba) + cb^4*(cba^4*(MHH^2 - MHL^2)*sb^2 + 2*cba*m122*sba + cba^2*(MHH^2 - MHL^2)*sb^2*sba^2 + (-MHH^2 + MHL^2)*sb^2*sba^4) + cb^2*sb^2*(cba^4*(MHH^2 - MHL^2)*sb^2 + 4*cba*m122*sba - (MHH^2 - MHL^2)*sba^2*(-1 + sb^2*sba^2) - cba^2*(MHH^2 - MHL^2)*(1 + sb^2*sba^2)) + cb*cba*sb^3*sba*(-2*MHp^2*sb^2 + MHL^2*(1 - 2*sb^2*sba^2) + MHH^2*(-1 + 2*sb^2*sba^2)) + cb^3*cba*sb*sba*(-4*MHp^2*sb^2 + MHL^2*(-1 + 2*cba^2*sb^2 - 2*sb^2*sba^2) + MHH^2*(1 - 2*cba^2*sb^2 + 2*sb^2*sba^2))))/(cb*sb*vev^2), 0}},

C[ S[2] , S[2] , S[2] , S[1] ] == {{((3*I)*(-(cba*sb) + cb*sba)*(cb*cba + sb*sba)*(m122*sb^6*sba^2 + cb^7*(MHH^2 - MHL^2)*sb*sba^4 + cb*sb^5*sba*(2*cba*m122 - MHH^2*sba + cba^2*(MHH^2 - MHL^2)*sb^2*sba) - cb^6*sba*(cba^3*(MHH^2 - MHL^2)*sb^2 + m122*sba + 3*cba*(MHH^2 - MHL^2)*sb^2*sba^2) - cb^4*sb^2*sba*(m122*sba + 4*cba*MHH^2*sb^2*sba^2 + cba*MHL^2*(2 - 4*sb^2*sba^2)) + cb^2*sb^4*sba*(cba^3*(MHH^2 - MHL^2)*sb^2 + m122*sba + cba*MHL^2*sb^2*sba^2 - cba*MHH^2*(2 + sb^2*sba^2)) + cb^3*cba*sb^3*(cba^3*(MHH^2 - MHL^2)*sb^2 + 4*m122*sba + cba*(MHH^2 - MHL^2)*(-1 + 2*sb^2*sba^2)) + cb^5*sb*(cba^4*(MHH^2 - MHL^2)*sb^2 + 2*cba*m122*sba + cba^2*(MHH^2 - MHL^2)*sb^2*sba^2 + MHH^2*sb^2*sba^4 + MHL^2*(sba^2 - sb^2*sba^4))))/(cb^3*sb^3*vev^2), 0}},

C[ S[5] , S[5] , -S[6] , S[4] ] == {{(I*(MHH - MHL)*(MHH + MHL)*(cb^4*cba*sba + 2*cb^2*cba*sb^2*sba + cba*sb^4*sba - cb^3*sb*(cba^2 + sba^2) + cb*(sb - sb^3*(cba^2 + sba^2))))/vev^2, 0}},

C[ S[6] , -S[6] , -S[6] , S[4] ] == {{((2*I)*(MHH - MHL)*(MHH + MHL)*(cb^4*cba*sba + 2*cb^2*cba*sb^2*sba + cba*sb^4*sba - cb^3*sb*(cba^2 + sba^2) + cb*(sb - sb^3*(cba^2 + sba^2))))/vev^2, 0}},

C[ -S[6] , S[2] , S[2] , S[4] ] == {{((-I)*(m122*sb^6*sba^2 + cb*sb^5*(-(cba^2*MHL^2*sb^2) + MHH^2*(-1 + cba^2*sb^2))*sba^2 + cb^7*(MHH^2 - MHL^2)*sb*sba^4 + cb^3*cba^2*(MHH^2 - MHL^2)*sb^3*(-1 + cba^2*sb^2 + 2*sb^2*sba^2) + cb^6*sba*(cba^3*(-MHH^2 + MHL^2)*sb^2 - m122*sba + cba*sb^2*(2*MHp^2 + 3*(-MHH^2 + MHL^2)*sba^2)) + cb^2*sb^4*sba*(cba^3*(MHH^2 - MHL^2)*sb^2 + m122*sba + cba*sb^2*(2*MHp^2 + MHL^2*sba^2) - cba*MHH^2*(2 + sb^2*sba^2)) + cb^4*sb^2*sba*(-(m122*sba) + 4*cba*sb^2*(MHp^2 - MHH^2*sba^2) + cba*MHL^2*(-2 + 4*sb^2*sba^2)) + cb^5*(cba^4*(MHH^2 - MHL^2)*sb^3 + cba^2*(MHH^2 - MHL^2)*sb^3*sba^2 + MHH^2*sb^3*sba^4 + MHL^2*(sb*sba^2 - sb^3*sba^4))))/(cb^2*sb^2*vev^2), 0}},

C[ S[5] , S[5] , S[6] , -S[4] ] == {{(I*(MHH - MHL)*(MHH + MHL)*(cb^4*cba*sba + 2*cb^2*cba*sb^2*sba + cba*sb^4*sba - cb^3*sb*(cba^2 + sba^2) + cb*(sb - sb^3*(cba^2 + sba^2))))/vev^2, 0}},

C[ S[6] , S[6] , -S[6] , -S[4] ] == {{((2*I)*(MHH - MHL)*(MHH + MHL)*(cb^4*cba*sba + 2*cb^2*cba*sb^2*sba + cba*sb^4*sba - cb^3*sb*(cba^2 + sba^2) + cb*(sb - sb^3*(cba^2 + sba^2))))/vev^2, 0}},

C[ S[6] , S[2] , S[2] , -S[4] ] == {{((-I)*(m122*sb^6*sba^2 + cb*sb^5*(-(cba^2*MHL^2*sb^2) + MHH^2*(-1 + cba^2*sb^2))*sba^2 + cb^7*(MHH^2 - MHL^2)*sb*sba^4 + cb^3*cba^2*(MHH^2 - MHL^2)*sb^3*(-1 + cba^2*sb^2 + 2*sb^2*sba^2) + cb^6*sba*(cba^3*(-MHH^2 + MHL^2)*sb^2 - m122*sba + cba*sb^2*(2*MHp^2 + 3*(-MHH^2 + MHL^2)*sba^2)) + cb^2*sb^4*sba*(cba^3*(MHH^2 - MHL^2)*sb^2 + m122*sba + cba*sb^2*(2*MHp^2 + MHL^2*sba^2) - cba*MHH^2*(2 + sb^2*sba^2)) + cb^4*sb^2*sba*(-(m122*sba) + 4*cba*sb^2*(MHp^2 - MHH^2*sba^2) + cba*MHL^2*(-2 + 4*sb^2*sba^2)) + cb^5*(cba^4*(MHH^2 - MHL^2)*sb^3 + cba^2*(MHH^2 - MHL^2)*sb^3*sba^2 + MHH^2*sb^3*sba^4 + MHL^2*(sb*sba^2 - sb^3*sba^4))))/(cb^2*sb^2*vev^2), 0}},

C[ S[5] , -S[6] , S[2] , S[4] ] == {{-(((MHA - MHp)*(MHA + MHp)*(cb^2 + sb^2)^2*sba)/vev^2), 0}},

C[ -S[6] , S[3] , S[1] , S[4] ] == {{-(((MHA - MHp)*(MHA + MHp)*(cb^2 + sb^2)^2*sba)/vev^2), 0}},

C[ S[5] , S[6] , S[2] , -S[4] ] == {{((MHA - MHp)*(MHA + MHp)*(cb^2 + sb^2)^2*sba)/vev^2, 0}},

C[ S[6] , S[3] , S[1] , -S[4] ] == {{((MHA - MHp)*(MHA + MHp)*(cb^2 + sb^2)^2*sba)/vev^2, 0}},

C[ S[3] , S[3] , S[1] ] == {{((-I)*(cba*m122*sb^6 + cb^5*sb*(cba*MHL^2 - 2*m122*sba) + cb^6*(-(cba*m122) + 2*MHA^2*sb^2*sba) + cb^3*(cba^3*(MHH^2 - MHL^2)*sb^5 - 4*m122*sb^3*sba + cba*(MHH^2 - MHL^2)*sb^5*sba^2) + cb^2*sb^4*(cba*m122 + cba^2*(-MHH^2 + MHL^2)*sb^2*sba + sb^2*sba*(2*MHA^2 + MHL^2*sba^2) + MHH^2*sba*(1 - sb^2*sba^2)) + cb*sb^5*(cba^3*(MHH^2 - MHL^2)*sb^2 - 2*m122*sba - cba*MHL^2*sb^2*sba^2 + cba*MHH^2*(-1 + sb^2*sba^2)) + cb^4*sb^2*(-(cba*m122) + cba^2*(-MHH^2 + MHL^2)*sb^2*sba + sb^2*sba*(4*MHA^2 - MHH^2*sba^2) + MHL^2*sba*(1 + sb^2*sba^2))))/(cb^2*sb^2*vev), 0}},

C[ S[1] , S[1] , S[1] ] == {{((3*I)*(-(cba^3*m122*sb^6) + cb^6*(cba^3*m122 + cba^2*(MHH^2 - MHL^2)*sb^2*sba^3 + (MHH^2 - MHL^2)*sb^2*sba^5) + cb*cba^2*sb^5*(cba^3*(-MHH^2 + MHL^2)*sb^2 + 2*m122*sba + cba*MHL^2*sb^2*sba^2 + cba*MHH^2*(1 - sb^2*sba^2)) + cb^3*cba*sb^3*(cba^4*(-MHH^2 + MHL^2)*sb^2 + 4*cba*m122*sba + 4*cba^2*(-MHH^2 + MHL^2)*sb^2*sba^2 - 3*(MHH^2 - MHL^2)*sba^2*(-1 + sb^2*sba^2)) + cb^2*sb^4*(-(cba^3*m122) + 3*cba^4*(MHH^2 - MHL^2)*sb^2*sba - MHL^2*sba^3 + 3*cba^2*(-(MHL^2*sb^2*sba^3) + MHH^2*sba*(-1 + sb^2*sba^2))) + cb^5*cba*sb*(2*cba*m122*sba + 3*(-MHH^2 + MHL^2)*sb^2*sba^4 + cba^2*(-3*MHH^2*sb^2*sba^2 + MHL^2*(-1 + 3*sb^2*sba^2))) + cb^4*sb^2*(cba^3*m122 + 3*cba^4*(MHH^2 - MHL^2)*sb^2*sba - MHL^2*sb^2*sba^5 + MHH^2*sba^3*(-1 + sb^2*sba^2) + cba^2*(4*MHH^2*sb^2*sba^3 - MHL^2*sba*(3 + 4*sb^2*sba^2)))))/(cb^2*sb^2*vev), 0}},

C[ S[1] , S[4] , -S[4] ] == {{((-I)*(cba*m122*sb^6 + cb^5*sb*(cba*MHL^2 - 2*m122*sba) + cb^6*(-(cba*m122) + 2*MHp^2*sb^2*sba) + cb^3*(cba^3*(MHH^2 - MHL^2)*sb^5 - 4*m122*sb^3*sba + cba*(MHH^2 - MHL^2)*sb^5*sba^2) + cb^2*sb^4*(cba*m122 + cba^2*(-MHH^2 + MHL^2)*sb^2*sba + sb^2*sba*(2*MHp^2 + MHL^2*sba^2) + MHH^2*sba*(1 - sb^2*sba^2)) + cb*sb^5*(cba^3*(MHH^2 - MHL^2)*sb^2 - 2*m122*sba - cba*MHL^2*sb^2*sba^2 + cba*MHH^2*(-1 + sb^2*sba^2)) + cb^4*sb^2*(-(cba*m122) + cba^2*(-MHH^2 + MHL^2)*sb^2*sba + sb^2*sba*(4*MHp^2 - MHH^2*sba^2) + MHL^2*sba*(1 + sb^2*sba^2))))/(cb^2*sb^2*vev), 0}},

C[ S[3] , S[3] , S[2] ] == {{(I*(4*cb^3*cba*m122*sb^3 + m122*sb^6*sba + cb^2*sb^4*(-(cba*(MHH^2 + 2*MHA^2*sb^2)) + m122*sba) + cb*sb^5*(2*cba*m122 - MHH^2*sba) + cb^7*(MHH^2 - MHL^2)*sb*sba*(cba^2 + sba^2) - cb^6*(cba^3*(MHH^2 - MHL^2)*sb^2 + m122*sba + cba*sb^2*(2*MHA^2 + (MHH^2 - MHL^2)*sba^2)) + cb^4*sb^2*(cba^3*(-MHH^2 + MHL^2)*sb^2 - m122*sba - cba*sb^2*(4*MHA^2 + MHH^2*sba^2) + cba*MHL^2*(-1 + sb^2*sba^2)) + cb^5*(2*cba*m122*sb + cba^2*(MHH^2 - MHL^2)*sb^3*sba + MHH^2*sb^3*sba^3 + MHL^2*(sb*sba - sb^3*sba^3))))/(cb^2*sb^2*vev), 0}},

C[ S[5] , S[3] , S[1] ] == {{(I*(cb^4*cba*MHA^2 - cb^3*(MHH^2 - MHL^2)*sb*sba*(cba^2 + sba^2) - cb*(MHH^2 - MHL^2)*sb*sba*(-1 + cba^2*sb^2 + sb^2*sba^2) + cb^2*(-(cba*MHL^2*(1 + cba^2*sb^2 + sb^2*sba^2)) + cba*sb^2*(2*MHA^2 + MHH^2*(cba^2 + sba^2))) + cba*sb^2*(MHH^2*(-1 + cba^2*sb^2 + sb^2*sba^2) + sb^2*(MHA^2 - MHL^2*(cba^2 + sba^2)))))/vev, 0}},

C[ -S[6] , S[3] , S[4] ] == {{-(((MHA - MHp)*(MHA + MHp)*(cb^2 + sb^2)^2)/vev), 0}},

C[ S[6] , S[3] , -S[4] ] == {{((MHA - MHp)*(MHA + MHp)*(cb^2 + sb^2)^2)/vev, 0}},

C[ S[5] , S[5] , S[2] ] == {{(I*(cb^2*cba*MHL^2*sb^2*(cba^2 + sba^2) - cba*MHH^2*sb^4*(cba^2 + sba^2) + cb^3*(MHH^2 - MHL^2)*sb*sba*(cba^2 + sba^2) + cba*MHL^2*sb^2*(-1 + cba^2*sb^2 + sb^2*sba^2) + cb*(MHH^2 - MHL^2)*sb*sba*(-1 + cba^2*sb^2 + sb^2*sba^2) - cb^2*cba*MHH^2*(1 + cba^2*sb^2 + sb^2*sba^2)))/vev, 0}},

C[ S[6] , -S[6] , S[2] ] == {{(I*(cb^2*cba*MHL^2*sb^2*(cba^2 + sba^2) - cba*MHH^2*sb^4*(cba^2 + sba^2) + cb^3*(MHH^2 - MHL^2)*sb*sba*(cba^2 + sba^2) + cba*MHL^2*sb^2*(-1 + cba^2*sb^2 + sb^2*sba^2) + cb*(MHH^2 - MHL^2)*sb*sba*(-1 + cba^2*sb^2 + sb^2*sba^2) - cb^2*cba*MHH^2*(1 + cba^2*sb^2 + sb^2*sba^2)))/vev, 0}},

C[ S[2] , S[2] , S[2] ] == {{((3*I)*(m122*sb^6*sba^3 + cb*sb^5*sba^2*(2*cba*m122 - MHH^2*sba) + cb^7*(MHH^2 - MHL^2)*sb*sba^3*(cba^2 + sba^2) - cb^6*sba^2*(3*cba^3*(MHH^2 - MHL^2)*sb^2 + m122*sba + 3*cba*(MHH^2 - MHL^2)*sb^2*sba^2) + cb^3*cba*sb^3*sba*(3*cba^3*(MHH^2 - MHL^2)*sb^2 + 4*m122*sba + 3*cba*(MHH^2 - MHL^2)*(-1 + sb^2*sba^2)) + cb^5*sb*sba*(3*cba^4*(MHH^2 - MHL^2)*sb^2 + 2*cba*m122*sba + 4*cba^2*(MHH^2 - MHL^2)*sb^2*sba^2 + MHH^2*sb^2*sba^4 + MHL^2*(sba^2 - sb^2*sba^4)) + cb^2*sb^4*(cba^5*(-MHH^2 + MHL^2)*sb^2 - 3*cba*MHH^2*sba^2 + m122*sba^3 + cba^3*(-(MHH^2*sb^2*sba^2) + MHL^2*(-1 + sb^2*sba^2))) - cb^4*sb^2*(cba^5*(MHH^2 - MHL^2)*sb^2 + m122*sba^3 + 3*cba*sba^2*(MHH^2*sb^2*sba^2 + MHL^2*(1 - sb^2*sba^2)) + cba^3*(-4*MHL^2*sb^2*sba^2 + MHH^2*(1 + 4*sb^2*sba^2)))))/(cb^2*sb^2*vev), 0}},

C[ S[2] , S[1] , S[1] ] == {{(I*(3*cba^2*m122*sb^6*sba + cb^7*cba^2*(MHH^2 - MHL^2)*sb*sba*(cba^2 + sba^2) + cb^6*cba*(cba^4*(-MHH^2 + MHL^2)*sb^2 - 3*cba*m122*sba + 3*cba^2*(MHH^2 - MHL^2)*sb^2*sba^2 + 4*(MHH^2 - MHL^2)*sb^2*sba^4) + cb^3*sb^3*(4*cba^3*m122 + 4*cba^4*(-MHH^2 + MHL^2)*sb^2*sba - 8*cba*m122*sba^2 - cba^2*(MHH^2 - MHL^2)*sba*(-6 + sb^2*sba^2) + 3*(MHH^2 - MHL^2)*sba^3*(-1 + sb^2*sba^2)) + cb*cba*sb^5*(2*cba^2*m122 + 2*cba^3*(MHH^2 - MHL^2)*sb^2*sba - 4*m122*sba^2 - 2*cba*MHL^2*sb^2*sba^3 + cba*MHH^2*sba*(-3 + 2*sb^2*sba^2)) - cb^4*cba*sb^2*(3*cba^2*MHL^2 + cba^4*(-MHH^2 + MHL^2)*sb^2 + 3*cba*m122*sba + sba^2*(MHH^2*(3 + sb^2*sba^2) - MHL^2*(6 + sb^2*sba^2))) + cb^5*sb*(2*cba^3*m122 + 5*cba^4*(-MHH^2 + MHL^2)*sb^2*sba - 4*cba*m122*sba^2 + 3*(MHH^2 - MHL^2)*sb^2*sba^5 + cba^2*(-2*MHH^2*sb^2*sba^3 + MHL^2*sba*(3 + 2*sb^2*sba^2))) + cb^2*cba*sb^4*(2*cba^4*(MHH^2 - MHL^2)*sb^2 + 3*cba*m122*sba - 3*cba^2*(-(MHL^2*sb^2*sba^2) + MHH^2*(1 + sb^2*sba^2)) + sba^2*(MHH^2*(6 - 5*sb^2*sba^2) + MHL^2*(-3 + 5*sb^2*sba^2)))))/(cb^2*sb^2*vev), 0}},

C[ S[2] , S[4] , -S[4] ] == {{(I*(4*cb^3*cba*m122*sb^3 + m122*sb^6*sba + cb^2*sb^4*(-(cba*(MHH^2 + 2*MHp^2*sb^2)) + m122*sba) + cb*sb^5*(2*cba*m122 - MHH^2*sba) + cb^7*(MHH^2 - MHL^2)*sb*sba*(cba^2 + sba^2) - cb^6*(cba^3*(MHH^2 - MHL^2)*sb^2 + m122*sba + cba*sb^2*(2*MHp^2 + (MHH^2 - MHL^2)*sba^2)) + cb^4*sb^2*(cba^3*(-MHH^2 + MHL^2)*sb^2 - m122*sba - cba*sb^2*(4*MHp^2 + MHH^2*sba^2) + cba*MHL^2*(-1 + sb^2*sba^2)) + cb^5*(2*cba*m122*sb + cba^2*(MHH^2 - MHL^2)*sb^3*sba + MHH^2*sb^3*sba^3 + MHL^2*(sb*sba - sb^3*sba^3))))/(cb^2*sb^2*vev), 0}},

C[ -S[6] , S[1] , S[4] ] == {{(I*(cb^4*cba*MHp^2 - cb^3*(MHH^2 - MHL^2)*sb*sba*(cba^2 + sba^2) - cb*(MHH^2 - MHL^2)*sb*sba*(-1 + cba^2*sb^2 + sb^2*sba^2) + cba*sb^2*(sb^2*(-(cba^2*MHL^2) + MHp^2 - MHL^2*sba^2) + MHH^2*(-1 + cba^2*sb^2 + sb^2*sba^2)) + cb^2*(cba*sb^2*(cba^2*MHH^2 + 2*MHp^2 + MHH^2*sba^2) - cba*MHL^2*(1 + cba^2*sb^2 + sb^2*sba^2))))/vev, 0}},

C[ S[6] , S[1] , -S[4] ] == {{(I*(cb^4*cba*MHp^2 - cb^3*(MHH^2 - MHL^2)*sb*sba*(cba^2 + sba^2) - cb*(MHH^2 - MHL^2)*sb*sba*(-1 + cba^2*sb^2 + sb^2*sba^2) + cba*sb^2*(sb^2*(-(cba^2*MHL^2) + MHp^2 - MHL^2*sba^2) + MHH^2*(-1 + cba^2*sb^2 + sb^2*sba^2)) + cb^2*(cba*sb^2*(cba^2*MHH^2 + 2*MHp^2 + MHH^2*sba^2) - cba*MHL^2*(1 + cba^2*sb^2 + sb^2*sba^2))))/vev, 0}},

C[ S[5] , S[3] , S[2] ] == {{(I*(sb^2*(MHH^2 - MHA^2*sb^2)*sba - cb^3*cba*(MHH^2 - MHL^2)*sb*(cba^2 + sba^2) - cb*cba*(MHH^2 - MHL^2)*sb*(-1 + cba^2*sb^2 + sb^2*sba^2) - cb^4*sba*(MHA^2 - (MHH^2 - MHL^2)*(cba^2 + sba^2)) + cb^2*sba*(-(MHL^2*(-1 + cba^2*sb^2 + sb^2*sba^2)) + sb^2*(-2*MHA^2 + MHH^2*(cba^2 + sba^2)))))/vev, 0}},

C[ S[5] , S[5] , S[1] ] == {{(I*(-(MHL^2*sb^2*sba) - cb^3*cba*(MHH^2 - MHL^2)*sb*(cba^2 + sba^2) + cb^4*(MHH^2 - MHL^2)*sba*(cba^2 + sba^2) - cb*cba*(MHH^2 - MHL^2)*sb*(-1 + cba^2*sb^2 + sb^2*sba^2) + cb^2*sba*(-(MHL^2*sb^2*(cba^2 + sba^2)) + MHH^2*(-1 + cba^2*sb^2 + sb^2*sba^2))))/vev, 0}},

C[ S[6] , -S[6] , S[1] ] == {{(I*(-(MHL^2*sb^2*sba) - cb^3*cba*(MHH^2 - MHL^2)*sb*(cba^2 + sba^2) + cb^4*(MHH^2 - MHL^2)*sba*(cba^2 + sba^2) - cb*cba*(MHH^2 - MHL^2)*sb*(-1 + cba^2*sb^2 + sb^2*sba^2) + cb^2*sba*(-(MHL^2*sb^2*(cba^2 + sba^2)) + MHH^2*(-1 + cba^2*sb^2 + sb^2*sba^2))))/vev, 0}},

C[ S[2] , S[2] , S[1] ] == {{((-I)*(3*cba*m122*sb^6*sba^2 + 2*cb^7*cba*(MHH^2 - MHL^2)*sb*sba^2*(cba^2 + sba^2) + cb^6*sba*(5*cba^4*(-MHH^2 + MHL^2)*sb^2 - 3*cba*m122*sba + 3*cba^2*(-MHH^2 + MHL^2)*sb^2*sba^2 + 2*(MHH^2 - MHL^2)*sb^2*sba^4) + cb*sb^5*sba*(4*cba^2*m122 + cba^3*(MHH^2 - MHL^2)*sb^2*sba - 2*m122*sba^2 - cba*MHL^2*sb^2*sba^3 + cba*MHH^2*sba*(-3 + sb^2*sba^2)) + cb^5*sb*(3*cba^5*(MHH^2 - MHL^2)*sb^2 + 4*cba^2*m122*sba + cba^3*(-MHH^2 + MHL^2)*sb^2*sba^2 - 2*m122*sba^3 - 4*cba*MHH^2*sb^2*sba^4 + cba*MHL^2*sba^2*(3 + 4*sb^2*sba^2)) + cb^3*sb^3*(3*cba^5*(MHH^2 - MHL^2)*sb^2 + 8*cba^2*m122*sba - 4*m122*sba^3 - cba^3*(MHH^2 - MHL^2)*(3 + 2*sb^2*sba^2) - cba*(MHH^2 - MHL^2)*sba^2*(-6 + 5*sb^2*sba^2)) + cb^4*sb^2*sba*(3*cba^2*(MHH^2 - 2*MHL^2) + cba^4*(-MHH^2 + MHL^2)*sb^2 - 3*cba*m122*sba + MHH^2*sb^2*sba^4 + MHL^2*(3*sba^2 - sb^2*sba^4)) + cb^2*sb^4*sba*(4*cba^4*(MHH^2 - MHL^2)*sb^2 + 3*cba*m122*sba + MHL^2*sb^2*sba^4 + MHH^2*(3*sba^2 - sb^2*sba^4) + 3*cba^2*(MHL^2*(1 - sb^2*sba^2) + MHH^2*(-2 + sb^2*sba^2)))))/(cb^2*sb^2*vev), 0}},

C[ -S[6] , S[2] , S[4] ] == {{(I*(sb^2*(MHH^2 - MHp^2*sb^2)*sba - cb^3*cba*(MHH^2 - MHL^2)*sb*(cba^2 + sba^2) + cb^4*sba*(cba^2*(MHH^2 - MHL^2) - MHp^2 + (MHH^2 - MHL^2)*sba^2) - cb*cba*(MHH^2 - MHL^2)*sb*(-1 + cba^2*sb^2 + sb^2*sba^2) + cb^2*sba*(sb^2*(cba^2*MHH^2 - 2*MHp^2 + MHH^2*sba^2) - MHL^2*(-1 + cba^2*sb^2 + sb^2*sba^2))))/vev, 0}},

C[ S[6] , S[2] , -S[4] ] == {{(I*(sb^2*(MHH^2 - MHp^2*sb^2)*sba - cb^3*cba*(MHH^2 - MHL^2)*sb*(cba^2 + sba^2) + cb^4*sba*(cba^2*(MHH^2 - MHL^2) - MHp^2 + (MHH^2 - MHL^2)*sba^2) - cb*cba*(MHH^2 - MHL^2)*sb*(-1 + cba^2*sb^2 + sb^2*sba^2) + cb^2*sba*(sb^2*(cba^2*MHH^2 - 2*MHp^2 + MHH^2*sba^2) - MHL^2*(-1 + cba^2*sb^2 + sb^2*sba^2))))/vev, 0}},

C[ S[6] , -S[6] , V[1] , V[1] ] == {{2*EL^2*(cb + I*sb)*(I*cb + sb), 0}},

C[ S[4] , -S[4] , V[1] , V[1] ] == {{2*EL^2*(cb + I*sb)*(I*cb + sb), 0}},

C[ S[6] , -S[6] , V[1] ] == {{EL*(cb + I*sb)*(I*cb + sb), 0}},

C[ S[4] , -S[4] , V[1] ] == {{EL*(cb + I*sb)*(I*cb + sb), 0}},

C[ S[5] , -S[6] , V[1] , V[3] ] == {{-1/2*(EL^2*(cb^2 + sb^2))/sw, 0}},

C[ -S[6] , S[2] , V[1] , V[3] ] == {{((I/2)*cba*EL^2*(cb^2 + sb^2))/sw, 0}},

C[ S[3] , -S[4] , V[1] , V[3] ] == {{-1/2*(EL^2*(cb^2 + sb^2))/sw, 0}},

C[ S[1] , -S[4] , V[1] , V[3] ] == {{((I/2)*cba*EL^2*(cb^2 + sb^2))/sw, 0}},

C[ -S[6] , S[1] , V[1] , V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*sba)/sw, 0}},

C[ S[2] , -S[4] , V[1] , V[3] ] == {{((-1/2*I)*EL^2*(cb^2 + sb^2)*sba)/sw, 0}},

C[ -S[6] , V[1] , V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*vev)/sw, 0}},

C[ S[5] , -S[6] , V[3] ] == {{-1/2*(EL*(cb^2 + sb^2))/sw, 0}},

C[ -S[6] , S[2] , V[3] ] == {{((-1/2*I)*cba*EL*(cb^2 + sb^2))/sw, 0}},

C[ -S[6] , S[1] , V[3] ] == {{((-1/2*I)*EL*(cb^2 + sb^2)*sba)/sw, 0}},

C[ S[3] , -S[4] , V[3] ] == {{-1/2*(EL*(cb^2 + sb^2))/sw, 0}},

C[ S[2] , -S[4] , V[3] ] == {{((-1/2*I)*EL*(cb^2 + sb^2)*sba)/sw, 0}},

C[ S[1] , -S[4] , V[3] ] == {{((I/2)*cba*EL*(cb^2 + sb^2))/sw, 0}},

C[ S[5] , S[6] , V[1] , -V[3] ] == {{(EL^2*(cb^2 + sb^2))/(2*sw), 0}},

C[ S[6] , S[2] , V[1] , -V[3] ] == {{((I/2)*cba*EL^2*(cb^2 + sb^2))/sw, 0}},

C[ S[3] , S[4] , V[1] , -V[3] ] == {{(EL^2*(cb^2 + sb^2))/(2*sw), 0}},

C[ S[1] , S[4] , V[1] , -V[3] ] == {{((I/2)*cba*EL^2*(cb^2 + sb^2))/sw, 0}},

C[ S[6] , S[1] , V[1] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*sba)/sw, 0}},

C[ S[2] , S[4] , V[1] , -V[3] ] == {{((-1/2*I)*EL^2*(cb^2 + sb^2)*sba)/sw, 0}},

C[ S[6] , V[1] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*vev)/sw, 0}},

C[ S[5] , S[6] , -V[3] ] == {{-1/2*(EL*(cb^2 + sb^2))/sw, 0}},

C[ S[6] , S[2] , -V[3] ] == {{((I/2)*cba*EL*(cb^2 + sb^2))/sw, 0}},

C[ S[6] , S[1] , -V[3] ] == {{((I/2)*EL*(cb^2 + sb^2)*sba)/sw, 0}},

C[ S[3] , S[4] , -V[3] ] == {{-1/2*(EL*(cb^2 + sb^2))/sw, 0}},

C[ S[2] , S[4] , -V[3] ] == {{((I/2)*EL*(cb^2 + sb^2)*sba)/sw, 0}},

C[ S[1] , S[4] , -V[3] ] == {{((-1/2*I)*cba*EL*(cb^2 + sb^2))/sw, 0}},

C[ S[5] , S[5] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2))/sw^2, 0}},

C[ S[6] , -S[6] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2))/sw^2, 0}},

C[ S[3] , S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2))/sw^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cba^2 + sba^2))/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cba^2 + sba^2))/sw^2, 0}},

C[ S[4] , -S[4] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2))/sw^2, 0}},

C[ S[2] , V[3] , -V[3] ] == {{((I/2)*cba*EL^2*(cb^2 + sb^2)*vev)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*sba*vev)/sw^2, 0}},

C[ S[6] , -S[6] , V[1] , V[2] ] == {{(I*EL^2*(cb^2 + sb^2)*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[4] , -S[4] , V[1] , V[2] ] == {{(I*EL^2*(cb^2 + sb^2)*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[5] , S[2] , V[2] ] == {{(cba*EL*(cb^2 + sb^2)*(cw^2 + sw^2))/(2*cw*sw), 0}},

C[ S[5] , S[1] , V[2] ] == {{(EL*(cb^2 + sb^2)*sba*(cw^2 + sw^2))/(2*cw*sw), 0}},

C[ S[6] , -S[6] , V[2] ] == {{((I/2)*EL*(cb^2 + sb^2)*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[3] , S[1] , V[2] ] == {{(cba*EL*(cb^2 + sb^2)*(cw^2 + sw^2))/(2*cw*sw), 0}},

C[ S[3] , S[2] , V[2] ] == {{-1/2*(EL*(cb^2 + sb^2)*sba*(cw^2 + sw^2))/(cw*sw), 0}},

C[ S[4] , -S[4] , V[2] ] == {{((I/2)*EL*(cb^2 + sb^2)*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[5] , -S[6] , V[3] , V[2] ] == {{(EL^2*(cb^2 + sb^2))/(2*cw), 0}},

C[ -S[6] , S[2] , V[3] , V[2] ] == {{((-1/2*I)*cba*EL^2*(cb^2 + sb^2))/cw, 0}},

C[ S[3] , -S[4] , V[3] , V[2] ] == {{(EL^2*(cb^2 + sb^2))/(2*cw), 0}},

C[ S[1] , -S[4] , V[3] , V[2] ] == {{((-1/2*I)*cba*EL^2*(cb^2 + sb^2))/cw, 0}},

C[ -S[6] , S[1] , V[3] , V[2] ] == {{((-1/2*I)*EL^2*(cb^2 + sb^2)*sba)/cw, 0}},

C[ S[2] , -S[4] , V[3] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*sba)/cw, 0}},

C[ -S[6] , V[3] , V[2] ] == {{((-1/2*I)*EL^2*(cb^2 + sb^2)*vev)/cw, 0}},

C[ S[5] , S[6] , -V[3] , V[2] ] == {{-1/2*(EL^2*(cb^2 + sb^2))/cw, 0}},

C[ S[6] , S[2] , -V[3] , V[2] ] == {{((-1/2*I)*cba*EL^2*(cb^2 + sb^2))/cw, 0}},

C[ S[3] , S[4] , -V[3] , V[2] ] == {{-1/2*(EL^2*(cb^2 + sb^2))/cw, 0}},

C[ S[1] , S[4] , -V[3] , V[2] ] == {{((-1/2*I)*cba*EL^2*(cb^2 + sb^2))/cw, 0}},

C[ S[6] , S[1] , -V[3] , V[2] ] == {{((-1/2*I)*EL^2*(cb^2 + sb^2)*sba)/cw, 0}},

C[ S[2] , S[4] , -V[3] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*sba)/cw, 0}},

C[ S[6] , -V[3] , V[2] ] == {{((-1/2*I)*EL^2*(cb^2 + sb^2)*vev)/cw, 0}},

C[ S[5] , S[5] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[6] , -S[6] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[3] , S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cba^2 + sba^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cba^2 + sba^2)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , -S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[2] , V[2] , V[2] ] == {{((I/2)*cba*EL^2*(cb^2 + sb^2)*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cb^2 + sb^2)*sba*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc157*IndexDelta[e1x2, e2x2], 0}, {I*gc157*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc158*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc158*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc159*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc159*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc160*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc160*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc161*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc161*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc162[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc163[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc164*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc165*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc166L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc166R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc167L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc167R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc168*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc169L*IndexDelta[e1x2, e2x2], 0}, {I*gc169R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[6] ] == {{I*gc170L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc170R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[4] ] == {{I*gc171L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc171R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[5] ] == {{gc172L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc172R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[2] ] == {{I*gc173L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc173R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[3] ] == {{gc174L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc174R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc175L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc175R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[6] ] == {{I*gc176[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[4] ] == {{I*gc177[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[5] ] == {{gc178L[e1x2, e2x2], 0}, {gc178R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[2] ] == {{I*gc179L[e1x2, e2x2], 0}, {I*gc179R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[3] ] == {{gc180L[e1x2, e2x2], 0}, {gc180R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc181L[e1x2, e2x2], 0}, {I*gc181R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[6] ] == {{I*gc182L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc182R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[4] ] == {{I*gc183L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc183R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[5] ] == {{gc184L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc184R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{I*gc185L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc185R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[3] ] == {{gc186L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc186R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc187L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc187R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[6] ] == {{0, 0}, {I*gc188R[e1x2, e2x2], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[4] ] == {{0, 0}, {I*gc189R[e1x2, e2x2], 0}},

C[ -U[1] , U[32] , V[3] ] == {{I*gc190, 0}, {0, 0}},

C[ -U[1] , U[31] , -V[3] ] == {{I*gc191, 0}, {0, 0}},

C[ -S[6] , -U[32] , U[1] ] == {{((-1/2*I)*EL^2*(cb^2 + sb^2)*vev)/sw, 0}},

C[ -U[32] , U[1] , -V[3] ] == {{I*gc193, 0}, {0, 0}},

C[ S[5] , -U[32] , U[32] ] == {{-1/4*(EL^2*(cb^2 + sb^2)*vev)/sw^2, 0}},

C[ S[2] , -U[32] , U[32] ] == {{((-1/4*I)*cba*EL^2*(cb^2 + sb^2)*vev)/sw^2, 0}},

C[ S[1] , -U[32] , U[32] ] == {{((-1/4*I)*EL^2*(cb^2 + sb^2)*sba*vev)/sw^2, 0}},

C[ -U[32] , U[32] , V[1] ] == {{I*gc197, 0}, {0, 0}},

C[ -U[32] , U[32] , V[2] ] == {{I*gc198, 0}, {0, 0}},

C[ -S[6] , -U[32] , U[2] ] == {{((-1/4*I)*EL^2*(cb^2 + sb^2)*(cw - sw)*(cw + sw)*vev)/(cw*sw^2), 0}},

C[ -U[32] , U[2] , -V[3] ] == {{I*gc200, 0}, {0, 0}},

C[ S[6] , -U[31] , U[1] ] == {{((-1/2*I)*EL^2*(cb^2 + sb^2)*vev)/sw, 0}},

C[ -U[31] , U[1] , V[3] ] == {{I*gc202, 0}, {0, 0}},

C[ S[5] , -U[31] , U[31] ] == {{(EL^2*(cb^2 + sb^2)*vev)/(4*sw^2), 0}},

C[ S[2] , -U[31] , U[31] ] == {{((-1/4*I)*cba*EL^2*(cb^2 + sb^2)*vev)/sw^2, 0}},

C[ S[1] , -U[31] , U[31] ] == {{((-1/4*I)*EL^2*(cb^2 + sb^2)*sba*vev)/sw^2, 0}},

C[ -U[31] , U[31] , V[1] ] == {{I*gc206, 0}, {0, 0}},

C[ -U[31] , U[31] , V[2] ] == {{I*gc207, 0}, {0, 0}},

C[ S[6] , -U[31] , U[2] ] == {{((-1/4*I)*EL^2*(cb^2 + sb^2)*(cw - sw)*(cw + sw)*vev)/(cw*sw^2), 0}},

C[ -U[31] , U[2] , V[3] ] == {{I*gc209, 0}, {0, 0}},

C[ S[6] , -U[2] , U[32] ] == {{((I/4)*EL^2*(cb^2 + sb^2)*(cw^2 + sw^2)*vev)/(cw*sw^2), 0}},

C[ -U[2] , U[32] , V[3] ] == {{I*gc211, 0}, {0, 0}},

C[ -S[6] , -U[2] , U[31] ] == {{((I/4)*EL^2*(cb^2 + sb^2)*(cw^2 + sw^2)*vev)/(cw*sw^2), 0}},

C[ -U[2] , U[31] , -V[3] ] == {{I*gc213, 0}, {0, 0}},

C[ S[2] , -U[2] , U[2] ] == {{((-1/4*I)*cba*EL^2*(cb^2 + sb^2)*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*EL^2*(cb^2 + sb^2)*sba*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -U[4, {e1x1}] , U[4, {e2x1}] , V[4, {e3x2}] ] == {{gc216*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc2 -> GS^2,
     gc4 -> EL^2,
     gc6 -> -(EL^2/sw^2),
     gc7 -> -((cw*EL^2)/sw),
     gc8 -> (cw^2*EL^2)/sw^2,
     gc157 -> -EL,
     gc158 -> (2*EL)/3,
     gc159 -> -1/3*EL,
     gc160 -> GS,
     gc161 -> GS,
     gc162[e1x2_, e2x2_] -> (EL*CKM[e1x2, e2x2])/(Sqrt[2]*sw),
     gc163[e1x2_, e2x2_] -> (EL*Conjugate[CKM[e2x2, e1x2]])/(Sqrt[2]*sw),
     gc164 -> EL/(Sqrt[2]*sw),
     gc165 -> EL/(Sqrt[2]*sw),
     gc166L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc166R -> (-2*EL*sw)/(3*cw),
     gc167L -> -1/6*(EL*(3*cw^2 + sw^2))/(cw*sw),
     gc167R -> (EL*sw)/(3*cw),
     gc168 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc169L -> -1/2*(EL*(cw^2 - sw^2))/(cw*sw),
     gc169R -> (EL*sw)/cw,
     gc170L[e1x2_, e2x2_] -> -((cb^2 + sb^2)*IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[yd[Generation$1, e1x2]], {Generation$1, 1, 3}]),
     gc170R[e1x2_, e2x2_] -> (cb^2 + sb^2)*IndexSum[Conjugate[CKM[Generation$1, e1x2]]*yu[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc171L[e1x2_, e2x2_] -> -((cb^2 + sb^2)*IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[rhod[Generation$1, e1x2]], {Generation$1, 1, 3}]),
     gc171R[e1x2_, e2x2_] -> (cb^2 + sb^2)*IndexSum[Conjugate[CKM[Generation$1, e1x2]]*rhou[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc172L[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*Conjugate[yd[e2x2, e1x2]])/Sqrt[2]),
     gc172R[e1x2_, e2x2_] -> ((cb^2 + sb^2)*yd[e1x2, e2x2])/Sqrt[2],
     gc173L[e1x2_, e2x2_] -> ((cb^2 + sb^2)*(sba*Conjugate[rhod[e2x2, e1x2]] - cba*Conjugate[yd[e2x2, e1x2]]))/Sqrt[2],
     gc173R[e1x2_, e2x2_] -> ((cb^2 + sb^2)*(sba*rhod[e1x2, e2x2] - cba*yd[e1x2, e2x2]))/Sqrt[2],
     gc174L[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*Conjugate[rhod[e2x2, e1x2]])/Sqrt[2]),
     gc174R[e1x2_, e2x2_] -> ((cb^2 + sb^2)*rhod[e1x2, e2x2])/Sqrt[2],
     gc175L[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*(cba*Conjugate[rhod[e2x2, e1x2]] + sba*Conjugate[yd[e2x2, e1x2]]))/Sqrt[2]),
     gc175R[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*(cba*rhod[e1x2, e2x2] + sba*yd[e1x2, e2x2]))/Sqrt[2]),
     gc176[e1x2_, e2x2_] -> -((cb^2 + sb^2)*Conjugate[yl[e2x2, e1x2]]),
     gc177[e1x2_, e2x2_] -> -((cb^2 + sb^2)*Conjugate[rhol[e2x2, e1x2]]),
     gc178L[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*Conjugate[yl[e2x2, e1x2]])/Sqrt[2]),
     gc178R[e1x2_, e2x2_] -> ((cb^2 + sb^2)*yl[e1x2, e2x2])/Sqrt[2],
     gc179L[e1x2_, e2x2_] -> ((cb^2 + sb^2)*(sba*Conjugate[rhol[e2x2, e1x2]] - cba*Conjugate[yl[e2x2, e1x2]]))/Sqrt[2],
     gc179R[e1x2_, e2x2_] -> ((cb^2 + sb^2)*(sba*rhol[e1x2, e2x2] - cba*yl[e1x2, e2x2]))/Sqrt[2],
     gc180L[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*Conjugate[rhol[e2x2, e1x2]])/Sqrt[2]),
     gc180R[e1x2_, e2x2_] -> ((cb^2 + sb^2)*rhol[e1x2, e2x2])/Sqrt[2],
     gc181L[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*(cba*Conjugate[rhol[e2x2, e1x2]] + sba*Conjugate[yl[e2x2, e1x2]]))/Sqrt[2]),
     gc181R[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*(cba*rhol[e1x2, e2x2] + sba*yl[e1x2, e2x2]))/Sqrt[2]),
     gc182L[e1x2_, e2x2_] -> (cb^2 + sb^2)*IndexSum[CKM[Generation$1, e2x2]*Conjugate[yu[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc182R[e1x2_, e2x2_] -> -((cb^2 + sb^2)*IndexSum[CKM[e1x2, Generation$1]*yd[Generation$1, e2x2], {Generation$1, 1, 3}]),
     gc183L[e1x2_, e2x2_] -> (cb^2 + sb^2)*IndexSum[CKM[Generation$1, e2x2]*Conjugate[rhou[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc183R[e1x2_, e2x2_] -> -((cb^2 + sb^2)*IndexSum[CKM[e1x2, Generation$1]*rhod[Generation$1, e2x2], {Generation$1, 1, 3}]),
     gc184L[e1x2_, e2x2_] -> ((cb^2 + sb^2)*Conjugate[yu[e2x2, e1x2]])/Sqrt[2],
     gc184R[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*yu[e1x2, e2x2])/Sqrt[2]),
     gc185L[e1x2_, e2x2_] -> ((cb^2 + sb^2)*(sba*Conjugate[rhou[e2x2, e1x2]] - cba*Conjugate[yu[e2x2, e1x2]]))/Sqrt[2],
     gc185R[e1x2_, e2x2_] -> ((cb^2 + sb^2)*(sba*rhou[e1x2, e2x2] - cba*yu[e1x2, e2x2]))/Sqrt[2],
     gc186L[e1x2_, e2x2_] -> ((cb^2 + sb^2)*Conjugate[rhou[e2x2, e1x2]])/Sqrt[2],
     gc186R[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*rhou[e1x2, e2x2])/Sqrt[2]),
     gc187L[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*(cba*Conjugate[rhou[e2x2, e1x2]] + sba*Conjugate[yu[e2x2, e1x2]]))/Sqrt[2]),
     gc187R[e1x2_, e2x2_] -> -(((cb^2 + sb^2)*(cba*rhou[e1x2, e2x2] + sba*yu[e1x2, e2x2]))/Sqrt[2]),
     gc188R[e1x2_, e2x2_] -> -((cb^2 + sb^2)*yl[e1x2, e2x2]),
     gc189R[e1x2_, e2x2_] -> -((cb^2 + sb^2)*rhol[e1x2, e2x2]),
     gc190 -> -EL,
     gc191 -> EL,
     gc193 -> -EL,
     gc197 -> EL,
     gc198 -> (cw*EL)/sw,
     gc200 -> -((cw*EL)/sw),
     gc202 -> EL,
     gc206 -> -EL,
     gc207 -> -((cw*EL)/sw),
     gc209 -> (cw*EL)/sw,
     gc211 -> -((cw*EL)/sw),
     gc213 -> (cw*EL)/sw,
     gc216 -> -GS};

